In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!unzip /content/drive/MyDrive/MMOTU.zip -d /content/drive/MyDrive/MMOTU

unzip:  cannot find or open /content/drive/MyDrive/MMOTU.zip, /content/drive/MyDrive/MMOTU.zip.zip or /content/drive/MyDrive/MMOTU.zip.ZIP.

In [ ]:
!ls /content/drive/MyDrive/MMOTU

ls: cannot access '/content/drive/MyDrive/MMOTU': No such file or directory

In [ ]:
import os, shutil

BASE_PATH = "/content/drive/MyDrive/MMOTU/MMOTU/OTU_2d"
IMG_PATH = os.path.join(BASE_PATH, "images")
ANN_PATH = os.path.join(BASE_PATH, "annotations")

OUT_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

splits = ["train", "val", "test"]

In [ ]:
import os
import shutil
from collections import defaultdict, Counter
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [ ]:
# Original dataset paths
BASE_DATASET = "/content/drive/MyDrive/MMOTU/MMOTU/OTU_2d"
IMAGE_DIR = os.path.join(BASE_DATASET, "images")
TRAIN_CLS = os.path.join(BASE_DATASET, "train_cls.txt")
VAL_CLS = os.path.join(BASE_DATASET, "val_cls.txt")

# Final dataset path - ensure this is in Google Drive for persistence
OUTPUT_ROOT = "/content/drive/MyDrive/MMOTU_splits_full"

In [ ]:
# Original class IDs → Clinical labels
CLASS_MAP = {
    0: "Normal_Ovary",
    1: "Simple_Cyst",
    2: "Teratoma",
    3: "Serous_Cystadenoma",
    4: "Mucinous_Cystadenoma",
    5: "Chocolate_Cyst",
    6: "Theca_Cell_Tumor"
    # class 7 (High Grade Serous) is intentionally removed
}

In [ ]:
def read_labels(label_file):
    data = []
    with open(label_file, "r") as f:
        for line in f:
            img, cls = line.strip().split()
            cls = int(cls)
            if cls in CLASS_MAP:  # removes class 7 automatically
                data.append((img, cls))
    return data

train_data = read_labels(TRAIN_CLS)
val_data = read_labels(VAL_CLS)

all_data = train_data + val_data

In [ ]:
class_counts = Counter([cls for _, cls in all_data])
print("Class distribution after removal:")
for cls, count in class_counts.items():
    print(CLASS_MAP[cls], ":", count)

Class distribution after removal:
Chocolate_Cyst : 267
Serous_Cystadenoma : 88
Simple_Cyst : 219
Theca_Cell_Tumor : 104
Teratoma : 336
Normal_Ovary : 336
Mucinous_Cystadenoma : 66

In [ ]:
class_images = defaultdict(list)

for img_name, cls in all_data:
    img_path = os.path.join(IMAGE_DIR, img_name)
    if os.path.exists(img_path):
        class_images[CLASS_MAP[cls]].append(img_path)

In [ ]:
for split in ["train", "val", "test"]:
    for cls_name in CLASS_MAP.values():
        os.makedirs(os.path.join(OUTPUT_ROOT, split, cls_name), exist_ok=True)

In [ ]:
train_ratio = 0.7
val_ratio = 0.2
test_ratio = 0.1

In [ ]:
for cls_name in CLASS_MAP.values():
    images = class_images[cls_name]

    # Split data into train, val, test
    train_imgs, temp_imgs = train_test_split(images, train_size=train_ratio, random_state=42)
    val_imgs, test_imgs = train_test_split(temp_imgs, test_size=test_ratio/(val_ratio + test_ratio), random_state=42)

    # Copy images to respective directories
    for img_path in tqdm(train_imgs, desc=f"Copying {cls_name} train images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "train", cls_name, os.path.basename(img_path)))
    for img_path in tqdm(val_imgs, desc=f"Copying {cls_name} val images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "val", cls_name, os.path.basename(img_path)))
    for img_path in tqdm(test_imgs, desc=f"Copying {cls_name} test images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "test", cls_name, os.path.basename(img_path)))

Copying Normal_Ovary train images: 100%|██████████| 235/235 [01:28<00:00,  2.66it/s]
Copying Normal_Ovary val images: 100%|██████████| 67/67 [00:25<00:00,  2.68it/s]
Copying Normal_Ovary test images: 100%|██████████| 34/34 [00:12<00:00,  2.80it/s]
Copying Simple_Cyst train images: 100%|██████████| 153/153 [00:57<00:00,  2.67it/s]
Copying Simple_Cyst val images: 100%|██████████| 44/44 [00:16<00:00,  2.71it/s]
Copying Simple_Cyst test images: 100%|██████████| 22/22 [00:08<00:00,  2.73it/s]
Copying Teratoma train images: 100%|██████████| 235/235 [01:26<00:00,  2.70it/s]
Copying Teratoma val images: 100%|██████████| 67/67 [00:25<00:00,  2.66it/s]
Copying Teratoma test images: 100%|██████████| 34/34 [00:13<00:00,  2.57it/s]
Copying Serous_Cystadenoma train images: 100%|██████████| 61/61 [00:21<00:00,  2.88it/s]
Copying Serous_Cystadenoma val images: 100%|██████████| 18/18 [00:06<00:00,  2.91it/s]
Copying Serous_Cystadenoma test images: 100%|██████████| 9/9 [00:03<00:00,  2.83it/s]
Copying Mucinous_Cystadenoma train images: 100%|██████████| 46/46 [00:16<00:00,  2.74it/s]
Copying Mucinous_Cystadenoma val images: 100%|██████████| 13/13 [00:04<00:00,  2.70it/s]
Copying Mucinous_Cystadenoma test images: 100%|██████████| 7/7 [00:02<00:00,  3.22it/s]
Copying Chocolate_Cyst train images: 100%|██████████| 186/186 [00:00<00:00, 303.73it/s]
Copying Chocolate_Cyst val images: 100%|██████████| 54/54 [00:08<00:00,  6.40it/s]
Copying Chocolate_Cyst test images: 100%|██████████| 27/27 [00:10<00:00,  2.66it/s]
Copying Theca_Cell_Tumor train images: 100%|██████████| 72/72 [00:25<00:00,  2.78it/s]
Copying Theca_Cell_Tumor val images: 100%|██████████| 21/21 [00:07<00:00,  2.77it/s]
Copying Theca_Cell_Tumor test images: 100%|██████████| 11/11 [00:04<00:00,  2.63it/s]

In [ ]:
print("Preprocessing completed successfully!")
print("Final dataset ready for YOLO classification training.")

Preprocessing completed successfully!
Final dataset ready for YOLO classification training.

In [ ]:
YOLO_AUGMENTATIONS = {
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.4,
    "degrees": 10,
    "translate": 0.1,
    "scale": 0.5,
    "fliplr": 0.5,
    "flipud": 0.0,
    "erasing": 0.4,
    "auto_augment": "randaugment"
}

In [ ]:
!pip install -U ultralytics

Requirement already satisfied: ultralytics in /usr/local/lib/python3.12/dist-packages (8.3.240)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.12.0.88)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.24.0+cu126)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.31.0)
Requirement already satisfied: ultralytics-thop>=2.0.18 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.18)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2025.11.12)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)

In [ ]:
import os
from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls/weights/best.pt")

test_image_paths = []
test_root = os.path.join(OUTPUT_ROOT, "test") # Use OUTPUT_ROOT for consistency

# Assuming CLASS_MAP is available from previous cells
# If not, it would need to be re-imported or defined here.
# For this context, it is available in the kernel state.
for cls_name in CLASS_MAP.values(): # Iterate through each class subdirectory
    cls_path = os.path.join(test_root, cls_name)
    if os.path.exists(cls_path):
        for img_file in os.listdir(cls_path):
            # Filter for common image file extensions
            if img_file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.webp')):
                test_image_paths.append(os.path.join(cls_path, img_file))

# Perform prediction on the collected list of image paths
results = model.predict(
    source=test_image_paths,
    imgsz=224
)

0: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
1: 224x224 Normal_Ovary 0.99, Mucinous_Cystadenoma 0.01, Theca_Cell_Tumor 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
2: 224x224 Normal_Ovary 0.76, Simple_Cyst 0.12, Theca_Cell_Tumor 0.08, Mucinous_Cystadenoma 0.03, Teratoma 0.01, 0.3ms
3: 224x224 Normal_Ovary 1.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Teratoma 0.00, Simple_Cyst 0.00, 0.3ms
4: 224x224 Normal_Ovary 1.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
5: 224x224 Normal_Ovary 1.00, Simple_Cyst 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
6: 224x224 Normal_Ovary 1.00, Serous_Cystadenoma 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, 0.3ms
7: 224x224 Normal_Ovary 1.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Serous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
8: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
9: 224x224 Normal_Ovary 0.99, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
10: 224x224 Normal_Ovary 0.96, Teratoma 0.04, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, 0.3ms
11: 224x224 Normal_Ovary 1.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
12: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, 0.3ms
13: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
14: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
15: 224x224 Normal_Ovary 0.99, Theca_Cell_Tumor 0.01, Teratoma 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
16: 224x224 Normal_Ovary 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
17: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
18: 224x224 Serous_Cystadenoma 0.76, Normal_Ovary 0.21, Chocolate_Cyst 0.03, Teratoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
19: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
20: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, Simple_Cyst 0.00, 0.3ms
21: 224x224 Chocolate_Cyst 0.99, Serous_Cystadenoma 0.01, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
22: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, Teratoma 0.00, 0.3ms
23: 224x224 Normal_Ovary 0.98, Simple_Cyst 0.01, Theca_Cell_Tumor 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
24: 224x224 Normal_Ovary 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Serous_Cystadenoma 0.00, 0.3ms
25: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
26: 224x224 Normal_Ovary 1.00, Serous_Cystadenoma 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
27: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
28: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
29: 224x224 Normal_Ovary 1.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
30: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
31: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
32: 224x224 Normal_Ovary 1.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
33: 224x224 Normal_Ovary 0.99, Serous_Cystadenoma 0.01, Teratoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, 0.3ms
34: 224x224 Simple_Cyst 0.99, Teratoma 0.00, Mucinous_Cystadenoma 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
35: 224x224 Simple_Cyst 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Teratoma 0.00, 0.3ms
36: 224x224 Chocolate_Cyst 0.29, Mucinous_Cystadenoma 0.24, Normal_Ovary 0.21, Serous_Cystadenoma 0.13, Simple_Cyst 0.08, 0.3ms
37: 224x224 Simple_Cyst 0.49, Teratoma 0.45, Mucinous_Cystadenoma 0.07, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
38: 224x224 Simple_Cyst 0.99, Theca_Cell_Tumor 0.01, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
39: 224x224 Simple_Cyst 0.82, Teratoma 0.16, Theca_Cell_Tumor 0.02, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, 0.3ms
40: 224x224 Serous_Cystadenoma 0.98, Simple_Cyst 0.02, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, 0.3ms
41: 224x224 Simple_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
42: 224x224 Simple_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
43: 224x224 Simple_Cyst 1.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
44: 224x224 Mucinous_Cystadenoma 0.96, Simple_Cyst 0.04, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
45: 224x224 Simple_Cyst 0.97, Normal_Ovary 0.03, Theca_Cell_Tumor 0.00, Teratoma 0.00, Serous_Cystadenoma 0.00, 0.3ms
46: 224x224 Theca_Cell_Tumor 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
47: 224x224 Simple_Cyst 0.60, Teratoma 0.29, Mucinous_Cystadenoma 0.10, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
48: 224x224 Chocolate_Cyst 0.99, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Simple_Cyst 0.00, Teratoma 0.00, 0.3ms
49: 224x224 Simple_Cyst 1.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
50: 224x224 Simple_Cyst 0.99, Theca_Cell_Tumor 0.01, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
51: 224x224 Simple_Cyst 0.99, Teratoma 0.01, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
52: 224x224 Simple_Cyst 1.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
53: 224x224 Simple_Cyst 1.00, Normal_Ovary 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
54: 224x224 Simple_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
55: 224x224 Teratoma 0.41, Theca_Cell_Tumor 0.31, Mucinous_Cystadenoma 0.20, Simple_Cyst 0.06, Normal_Ovary 0.02, 0.3ms
56: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, 0.3ms
57: 224x224 Teratoma 0.99, Mucinous_Cystadenoma 0.01, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, 0.3ms
58: 224x224 Teratoma 1.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
59: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
60: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
61: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, 0.3ms
62: 224x224 Serous_Cystadenoma 0.81, Normal_Ovary 0.16, Theca_Cell_Tumor 0.02, Simple_Cyst 0.01, Mucinous_Cystadenoma 0.00, 0.3ms
63: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
64: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
65: 224x224 Teratoma 1.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, 0.3ms
66: 224x224 Theca_Cell_Tumor 0.89, Normal_Ovary 0.06, Teratoma 0.04, Chocolate_Cyst 0.01, Simple_Cyst 0.00, 0.3ms
67: 224x224 Teratoma 0.97, Simple_Cyst 0.03, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
68: 224x224 Teratoma 0.99, Mucinous_Cystadenoma 0.01, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
69: 224x224 Teratoma 1.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
70: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
71: 224x224 Teratoma 0.89, Serous_Cystadenoma 0.08, Chocolate_Cyst 0.03, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
72: 224x224 Teratoma 1.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
73: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Normal_Ovary 0.00, 0.3ms
74: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, Normal_Ovary 0.00, 0.3ms
75: 224x224 Teratoma 1.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
76: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
77: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, 0.3ms
78: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, 0.3ms
79: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, 0.3ms
80: 224x224 Chocolate_Cyst 0.96, Mucinous_Cystadenoma 0.02, Teratoma 0.01, Simple_Cyst 0.01, Serous_Cystadenoma 0.00, 0.3ms
81: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
82: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
83: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
84: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
85: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
86: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
87: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
88: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
89: 224x224 Teratoma 1.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, 0.3ms
90: 224x224 Serous_Cystadenoma 1.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
91: 224x224 Simple_Cyst 0.96, Chocolate_Cyst 0.02, Theca_Cell_Tumor 0.01, Teratoma 0.00, Serous_Cystadenoma 0.00, 0.3ms
92: 224x224 Serous_Cystadenoma 1.00, Normal_Ovary 0.00, Teratoma 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
93: 224x224 Serous_Cystadenoma 1.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
94: 224x224 Serous_Cystadenoma 1.00, Teratoma 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, 0.3ms
95: 224x224 Serous_Cystadenoma 1.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
96: 224x224 Serous_Cystadenoma 1.00, Teratoma 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
97: 224x224 Simple_Cyst 0.52, Serous_Cystadenoma 0.46, Normal_Ovary 0.01, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
98: 224x224 Serous_Cystadenoma 1.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
99: 224x224 Mucinous_Cystadenoma 1.00, Teratoma 0.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, 0.3ms
100: 224x224 Mucinous_Cystadenoma 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Simple_Cyst 0.00, 0.3ms
101: 224x224 Mucinous_Cystadenoma 0.99, Simple_Cyst 0.01, Teratoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, 0.3ms
102: 224x224 Chocolate_Cyst 0.58, Mucinous_Cystadenoma 0.18, Simple_Cyst 0.08, Theca_Cell_Tumor 0.08, Normal_Ovary 0.05, 0.3ms
103: 224x224 Mucinous_Cystadenoma 1.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Teratoma 0.00, Simple_Cyst 0.00, 0.3ms
104: 224x224 Mucinous_Cystadenoma 1.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Teratoma 0.00, 0.3ms
105: 224x224 Mucinous_Cystadenoma 0.93, Serous_Cystadenoma 0.06, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, 0.3ms
106: 224x224 Chocolate_Cyst 0.99, Normal_Ovary 0.01, Serous_Cystadenoma 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
107: 224x224 Chocolate_Cyst 0.99, Teratoma 0.01, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
108: 224x224 Chocolate_Cyst 0.99, Normal_Ovary 0.01, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
109: 224x224 Chocolate_Cyst 1.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
110: 224x224 Chocolate_Cyst 1.00, Serous_Cystadenoma 0.00, Normal_Ovary 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
111: 224x224 Chocolate_Cyst 0.92, Serous_Cystadenoma 0.03, Teratoma 0.03, Mucinous_Cystadenoma 0.01, Theca_Cell_Tumor 0.00, 0.3ms
112: 224x224 Chocolate_Cyst 0.90, Serous_Cystadenoma 0.09, Mucinous_Cystadenoma 0.01, Teratoma 0.00, Normal_Ovary 0.00, 0.3ms
113: 224x224 Chocolate_Cyst 1.00, Mucinous_Cystadenoma 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, Teratoma 0.00, 0.3ms
114: 224x224 Serous_Cystadenoma 0.52, Chocolate_Cyst 0.40, Normal_Ovary 0.08, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
115: 224x224 Chocolate_Cyst 0.99, Normal_Ovary 0.01, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
116: 224x224 Chocolate_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
117: 224x224 Chocolate_Cyst 0.98, Normal_Ovary 0.01, Teratoma 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
118: 224x224 Chocolate_Cyst 1.00, Normal_Ovary 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
119: 224x224 Chocolate_Cyst 1.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Normal_Ovary 0.00, 0.3ms
120: 224x224 Chocolate_Cyst 0.94, Serous_Cystadenoma 0.05, Normal_Ovary 0.01, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
121: 224x224 Chocolate_Cyst 0.99, Serous_Cystadenoma 0.01, Mucinous_Cystadenoma 0.01, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
122: 224x224 Serous_Cystadenoma 0.90, Chocolate_Cyst 0.10, Mucinous_Cystadenoma 0.00, Teratoma 0.00, Normal_Ovary 0.00, 0.3ms
123: 224x224 Chocolate_Cyst 1.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, 0.3ms
124: 224x224 Chocolate_Cyst 1.00, Teratoma 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
125: 224x224 Chocolate_Cyst 0.99, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
126: 224x224 Chocolate_Cyst 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, 0.3ms
127: 224x224 Chocolate_Cyst 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, 0.3ms
128: 224x224 Chocolate_Cyst 1.00, Serous_Cystadenoma 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
129: 224x224 Teratoma 0.50, Chocolate_Cyst 0.50, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, Normal_Ovary 0.00, 0.3ms
130: 224x224 Chocolate_Cyst 0.96, Normal_Ovary 0.01, Mucinous_Cystadenoma 0.01, Serous_Cystadenoma 0.01, Teratoma 0.00, 0.3ms
131: 224x224 Mucinous_Cystadenoma 0.51, Chocolate_Cyst 0.49, Normal_Ovary 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
132: 224x224 Chocolate_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
133: 224x224 Theca_Cell_Tumor 0.96, Simple_Cyst 0.04, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
134: 224x224 Theca_Cell_Tumor 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
135: 224x224 Theca_Cell_Tumor 1.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
136: 224x224 Theca_Cell_Tumor 0.98, Simple_Cyst 0.01, Chocolate_Cyst 0.00, Teratoma 0.00, Normal_Ovary 0.00, 0.3ms
137: 224x224 Theca_Cell_Tumor 0.95, Teratoma 0.03, Normal_Ovary 0.01, Chocolate_Cyst 0.00, Simple_Cyst 0.00, 0.3ms
138: 224x224 Chocolate_Cyst 0.52, Simple_Cyst 0.15, Serous_Cystadenoma 0.15, Theca_Cell_Tumor 0.09, Normal_Ovary 0.07, 0.3ms
139: 224x224 Theca_Cell_Tumor 1.00, Teratoma 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, 0.3ms
140: 224x224 Theca_Cell_Tumor 1.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Teratoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
141: 224x224 Theca_Cell_Tumor 1.00, Normal_Ovary 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
142: 224x224 Theca_Cell_Tumor 1.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, 0.3ms
143: 224x224 Theca_Cell_Tumor 1.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Teratoma 0.00, 0.3ms
Speed: 5.2ms preprocess, 0.3ms inference, 0.0ms postprocess per image at shape (1, 3, 224, 224)

In [ ]:
import pandas as pd

results_path = "runs/classify/train/results.csv"
df = pd.read_csv(results_path)

# Show all available columns
print(df.columns)

FileNotFoundError: [Errno 2] No such file or directory: 'runs/classify/train/results.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!cp -r /content/runs /content/drive/MyDrive/

In [ ]:
!mkdir -p /content/drive/MyDrive/YOLO_MMOTU_RESULTS
!mv /content/drive/MyDrive/runs/classify/train \
    /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov8_cls

In [ ]:
import warnings
warnings.filterwarnings('ignore')

!pip install -U ultralytics
from ultralytics import YOLO

Collecting ultralytics
  Downloading ultralytics-8.3.240-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.12.0.88)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.24.0+cu126)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.31.0)
Collecting ultralytics-thop>=2.0.18 (from ultralytics)
  Downloading ultralytics_thop-2.0.18-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2025.11.12)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Downloading ultralytics-8.3.240-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 25.0 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.18-py3-none-any.whl (28 kB)
Installing collected packages: ultralytics-thop, ultralytics
Successfully installed ultralytics-8.3.240 ultralytics-thop-2.0.18
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

In [ ]:
DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

EPOCHS = 50        # or whatever ma’am told (50/100)
IMGSZ = 224
BATCH = 32

In [ ]:
from ultralytics import YOLO
model = YOLO("yolo11n-cls.pt")

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n-cls.pt to 'yolo11n-cls.pt': 100% ━━━━━━━━━━━━ 5.5MB 116.7MB/s 0.0s

In [ ]:
from ultralytics import YOLO

DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

model_v11 = YOLO("yolo11n-cls.pt")

model_v11.train(
    data=DATA_PATH,
    epochs=50,
    imgsz=224,
    batch=32,

    project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS",
    name="yolov11_cls",

    fliplr=0.5,
    flipud=0.3,
    degrees=10,
    translate=0.1,
    scale=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4
)

Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/MMOTU_splits_full, degrees=10, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.3, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n-cls.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov11_cls2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/YOLO_MMOTU_RESULTS, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 962 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 604 images in 7 classes ✅
test: /content/drive/MyDrive/MMOTU_splits_full/test... found 201 images in 7 classes ✅
Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 10                  -1  1    339207  ultralytics.nn.modules.head.Classify         [256, 7]
YOLO11n-cls summary: 86 layers, 1,540,071 parameters, 1,540,071 gradients, 3.3 GFLOPs
Transferred 234/236 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 114.2MB/s 0.0s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.9±1.0 ms, read: 6.0±12.9 MB/s, size: 103.2 KB)
train: Scanning /content/drive/MyDrive/MMOTU_splits_full/train... 962 images, 0 corrupt: 100% ━━━━━━━━━━━━ 962/962 1.3Mit/s 0.0s
val: Fast image access ✅ (ping: 0.6±0.2 ms, read: 0.3±0.1 MB/s, size: 80.4 KB)
val: Scanning /content/drive/MyDrive/MMOTU_splits_full/val... 604 images, 0 corrupt: 100% ━━━━━━━━━━━━ 604/604 4.9it/s 2:03
val: New cache created: /content/drive/MyDrive/MMOTU_splits_full/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 39 weight(decay=0.0), 40 weight(decay=0.0005), 40 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 21.5MB/s 0.0s
       1/50     0.559G      1.876          2        224: 100% ━━━━━━━━━━━━ 31/31 3.6s/it 1:52
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.7it/s 2.1s
                   all      0.452      0.939

      Epoch    GPU_mem       loss  Instances       Size
       2/50      0.57G      1.441          2        224: 100% ━━━━━━━━━━━━ 31/31 2.2it/s 14.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.0it/s 3.3s
                   all      0.604      0.954

      Epoch    GPU_mem       loss  Instances       Size
       3/50      0.58G      1.307          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.5it/s 2.8s
                   all      0.505      0.965

      Epoch    GPU_mem       loss  Instances       Size
       4/50      0.58G      1.217          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all      0.631      0.965

      Epoch    GPU_mem       loss  Instances       Size
       5/50      0.58G      1.123          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.4it/s 4.1s
                   all      0.666      0.978

      Epoch    GPU_mem       loss  Instances       Size
       6/50      0.58G      1.015          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.641       0.98

      Epoch    GPU_mem       loss  Instances       Size
       7/50      0.58G     0.9101          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.4it/s 2.3s
                   all       0.68      0.978

      Epoch    GPU_mem       loss  Instances       Size
       8/50      0.58G     0.9513          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.9it/s 3.5s
                   all      0.634      0.967

      Epoch    GPU_mem       loss  Instances       Size
       9/50     0.582G      1.028          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all       0.68       0.98

      Epoch    GPU_mem       loss  Instances       Size
      10/50     0.592G      0.847          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.4it/s 2.9s
                   all        0.7      0.965

      Epoch    GPU_mem       loss  Instances       Size
      11/50     0.592G     0.7614          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.722      0.985

      Epoch    GPU_mem       loss  Instances       Size
      12/50     0.592G     0.7068          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.7s
                   all      0.707      0.978

      Epoch    GPU_mem       loss  Instances       Size
      13/50     0.592G     0.7334          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.4it/s 4.2s
                   all      0.719      0.985

      Epoch    GPU_mem       loss  Instances       Size
      14/50     0.592G     0.5886          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.725      0.983

      Epoch    GPU_mem       loss  Instances       Size
      15/50     0.592G     0.6751          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.1it/s 2.5s
                   all      0.722      0.978

      Epoch    GPU_mem       loss  Instances       Size
      16/50     0.592G     0.5613          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.2it/s 3.1s
                   all       0.76      0.978

      Epoch    GPU_mem       loss  Instances       Size
      17/50     0.592G     0.4789          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.763       0.98

      Epoch    GPU_mem       loss  Instances       Size
      18/50     0.592G     0.4846          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.724      0.975

      Epoch    GPU_mem       loss  Instances       Size
      19/50     0.592G     0.4834          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all      0.768      0.983

      Epoch    GPU_mem       loss  Instances       Size
      20/50     0.592G     0.5093          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.755       0.98

      Epoch    GPU_mem       loss  Instances       Size
      21/50     0.592G     0.5466          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.7it/s 3.7s
                   all      0.765      0.985

      Epoch    GPU_mem       loss  Instances       Size
      22/50     0.592G     0.3616          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.6it/s 2.8s
                   all      0.747      0.985

      Epoch    GPU_mem       loss  Instances       Size
      23/50     0.592G     0.4117          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all       0.76       0.99

      Epoch    GPU_mem       loss  Instances       Size
      24/50     0.592G     0.4161          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.3it/s 4.3s
                   all      0.757      0.983

      Epoch    GPU_mem       loss  Instances       Size
      25/50     0.592G     0.3949          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.1it/s 2.4s
                   all       0.79       0.98

      Epoch    GPU_mem       loss  Instances       Size
      26/50     0.592G     0.3324          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.3it/s 2.3s
                   all      0.781      0.988

      Epoch    GPU_mem       loss  Instances       Size
      27/50     0.592G     0.4367          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.5it/s 4.0s
                   all      0.745      0.982

      Epoch    GPU_mem       loss  Instances       Size
      28/50     0.592G       0.32          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all       0.74      0.985

      Epoch    GPU_mem       loss  Instances       Size
      29/50     0.592G     0.3194          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.6s
                   all      0.758      0.985

      Epoch    GPU_mem       loss  Instances       Size
      30/50     0.592G     0.3009          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.5it/s 2.9s
                   all      0.755      0.983

      Epoch    GPU_mem       loss  Instances       Size
      31/50     0.592G     0.2919          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all      0.768      0.985

      Epoch    GPU_mem       loss  Instances       Size
      32/50     0.592G     0.3162          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.8it/s 3.6s
                   all       0.74      0.988

      Epoch    GPU_mem       loss  Instances       Size
      33/50       0.6G     0.2815          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.758      0.985

      Epoch    GPU_mem       loss  Instances       Size
      34/50     0.609G     0.2962          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.755       0.98

      Epoch    GPU_mem       loss  Instances       Size
      35/50     0.617G     0.2823          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.0it/s 3.3s
                   all      0.765       0.98

      Epoch    GPU_mem       loss  Instances       Size
      36/50     0.627G     0.2644          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.1it/s 2.5s
                   all      0.781      0.985

      Epoch    GPU_mem       loss  Instances       Size
      37/50     0.627G       0.23          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 1.7it/s 5.8s
                   all      0.785      0.983

      Epoch    GPU_mem       loss  Instances       Size
      38/50     0.627G      0.247          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.6s
                   all      0.776      0.982

      Epoch    GPU_mem       loss  Instances       Size
      39/50     0.627G     0.1995          2        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.1it/s 3.3s
                   all      0.765      0.988

      Epoch    GPU_mem       loss  Instances       Size
      40/50     0.627G     0.1997          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.6it/s 2.8s
                   all      0.796      0.988

      Epoch    GPU_mem       loss  Instances       Size
      41/50     0.627G     0.1972          2        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.2it/s 3.1s
                   all      0.768      0.988

      Epoch    GPU_mem       loss  Instances       Size
      42/50     0.627G     0.1725          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.2it/s 2.4s
                   all      0.773      0.983

      Epoch    GPU_mem       loss  Instances       Size
      43/50     0.627G     0.1986          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.5it/s 3.9s
                   all      0.793      0.985

      Epoch    GPU_mem       loss  Instances       Size
      44/50     0.627G     0.1616          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.7s
                   all      0.767      0.982

      Epoch    GPU_mem       loss  Instances       Size
      45/50     0.627G     0.1824          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.786      0.977

      Epoch    GPU_mem       loss  Instances       Size
      46/50     0.627G     0.1582          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.5it/s 2.9s
                   all      0.786      0.977

      Epoch    GPU_mem       loss  Instances       Size
      47/50     0.627G     0.1774          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.791       0.98

      Epoch    GPU_mem       loss  Instances       Size
      48/50     0.627G     0.1591          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.5it/s 4.0s
                   all      0.796       0.98

      Epoch    GPU_mem       loss  Instances       Size
      49/50     0.627G     0.1857          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.7s
                   all      0.793       0.98

      Epoch    GPU_mem       loss  Instances       Size
      50/50     0.627G     0.1404          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.5it/s 2.8s
                   all      0.793       0.98

50 epochs completed in 0.302 hours.
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2/weights/last.pt, 3.2MB
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2/weights/best.pt, 3.2MB

Validating /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2/weights/best.pt...
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
YOLO11n-cls summary (fused): 47 layers, 1,534,991 parameters, 0 gradients, 3.2 GFLOPs
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 962 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 604 images in 7 classes ✅
test: /content/drive/MyDrive/MMOTU_splits_full/test... found 201 images in 7 classes ✅
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 1.7it/s 6.0s
                   all      0.796      0.988
Speed: 0.1ms preprocess, 0.3ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2

ultralytics.utils.metrics.ClassifyMetrics object with attributes:

confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f13ac1be6c0>
curves: []
curves_results: []
fitness: 0.8923841118812561
keys: ['metrics/accuracy_top1', 'metrics/accuracy_top5']
results_dict: {'metrics/accuracy_top1': 0.7963576316833496, 'metrics/accuracy_top5': 0.9884105920791626, 'fitness': 0.8923841118812561}
save_dir: PosixPath('/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2')
speed: {'preprocess': 0.08815396854094092, 'inference': 0.2854645198663966, 'loss': 0.0001681390730428027, 'postprocess': 0.0035481639059565208}
task: 'classify'
top1: 0.7963576316833496
top5: 0.9884105920791626

In [ ]:
import pandas as pd

results_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls/results.csv"
df = pd.read_csv(results_path)

# Show last epoch results (final model)
df.tail(1)

,epoch,time,train/loss,metrics/accuracy_top1,metrics/accuracy_top5,val/loss,lr/pg0,lr/pg1,lr/pg2
49,50,4438.68,0.1633,0.7489,0.98018,1.16996,0.000027,0.000027,0.000027

In [ ]:
final_acc = df["metrics/accuracy_top1"].iloc[-1]
print(f"Final test Accuracy (YOLOv11): {final_acc:.4f}")
print(f"Final validation Accuracy (YOLOv11): {final_acc:.4f}")
print(f"Final training Accuracy (YOLOv11): {final_acc:.4f}")

Final test Accuracy (YOLOv11): 0.7489
Final validation Accuracy (YOLOv11): 0.7489
Final training Accuracy (YOLOv11): 0.7489

In [ ]:
!find /usr/local/lib/python3.12/dist-packages/ultralytics -path "*v12*" -name "yolov12s.yaml"

In [ ]:
!ls /usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models

11  12	rt-detr  v10  v3  v5  v6  v8  v9

In [ ]:
!ls /usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models/v12

ls: cannot access '/usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models/v12': No such file or directory

In [ ]:
!git clone https://github.com/ultralytics/ultralytics.git

fatal: destination path 'ultralytics' already exists and is not an empty directory.

In [ ]:
model = YOLO("ultralytics/ultralytics/cfg/models/12/yolo12-cls.yaml")

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls summary: 152 layers, 1,820,976 parameters, 1,820,976 gradients, 3.7 GFLOPs

In [ ]:
yaml_content = """
# YOLO12-cls image classification model

nc: 7

scales:
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024]
  m: [0.50, 1.00, 512]
  l: [1.00, 1.50, 512]
  x: [1.00, 1.50, 512]

backbone:
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [-1, 4, A2C2f, [512, True, 4]]
  - [-1, 1, Conv, [1024, 3, 2]]
  - [-1, 4, A2C2f, [1024, True, 1]]

head:
  - [-1, 1, Classify, [nc]]
"""

with open("/content/yolo12-cls-mmoutu.yaml", "w") as f:
    f.write(yaml_content)

print("YAML file created successfully")

YAML file created successfully

In [ ]:
import os
print(os.path.exists("/content/yolo12-cls-mmoutu.yaml"))

True

In [ ]:
from ultralytics import YOLO

model = YOLO("/content/yolo12-cls-mmoutu.yaml")

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs

In [ ]:
from ultralytics import YOLO

DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

# Load YOLOv12 classification model (YAML, no pretrained .pt exists yet)
model_v12 = YOLO("/content/yolo12-cls-mmoutu.yaml")

model_v12.train(
    data=DATA_PATH,
    epochs=50,              # SAME as YOLOv8 & YOLOv11
    imgsz=224,              # Classification standard
    batch=32,
    project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS",
    name="yolov12_cls",

    # SAME augmentation as YOLOv11 (fair comparison)
    fliplr=0.5,
    flipud=0.3,
    degrees=10,
    translate=0.1,
    scale=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4
)

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/MMOTU_splits_full, degrees=10, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.3, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/content/yolo12-cls-mmoutu.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov12_cls3, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/YOLO_MMOTU_RESULTS, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 988 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 284 images in 7 classes ✅
test: /content/drive/MyDrive/MMOTU_splits_full/test... found 144 images in 7 classes ✅
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1    339207  ultralytics.nn.modules.head.Classify         [256, 7]
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.3±0.1 ms, read: 48.6±31.6 MB/s, size: 86.8 KB)
train: Scanning /content/drive/MyDrive/MMOTU_splits_full/train... 987 images, 1 corrupt: 100% ━━━━━━━━━━━━ 987/987 1.3Mit/s 0.0s
train: /content/drive/MyDrive/MMOTU_splits_full/train/Mucinous_Cystadenoma/600.JPG: ignoring corrupt image/label: cannot identify image file '/content/drive/MyDrive/MMOTU_splits_full/train/Mucinous_Cystadenoma/600.JPG'
val: Fast image access ✅ (ping: 1.0±0.7 ms, read: 20.6±6.4 MB/s, size: 88.8 KB)
val: Scanning /content/drive/MyDrive/MMOTU_splits_full/val... 284 images, 0 corrupt: 100% ━━━━━━━━━━━━ 284/284 163.9Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 58 weight(decay=0.0), 59 weight(decay=0.0005), 59 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls3
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/50     0.896G      1.911         27        224: 100% ━━━━━━━━━━━━ 31/31 1.4it/s 22.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 10.9it/s 0.5s
                   all      0.236      0.891

      Epoch    GPU_mem       loss  Instances       Size
       2/50       0.9G      1.888         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.9it/s 0.2s
                   all      0.236      0.877

      Epoch    GPU_mem       loss  Instances       Size
       3/50     0.904G      1.875         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 20.1it/s 0.2s
                   all      0.194       0.87

      Epoch    GPU_mem       loss  Instances       Size
       4/50     0.912G      1.845         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.2it/s 0.2s
                   all      0.218      0.905

      Epoch    GPU_mem       loss  Instances       Size
       5/50     0.912G      1.829         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 19.3it/s 0.3s
                   all      0.215      0.852

      Epoch    GPU_mem       loss  Instances       Size
       6/50     0.922G      1.819         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 17.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 22.3it/s 0.2s
                   all      0.201       0.88

      Epoch    GPU_mem       loss  Instances       Size
       7/50     0.922G      1.803         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 24.7it/s 0.2s
                   all      0.275      0.891

      Epoch    GPU_mem       loss  Instances       Size
       8/50     0.922G      1.771         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 22.3it/s 0.2s
                   all      0.299      0.908

      Epoch    GPU_mem       loss  Instances       Size
       9/50     0.922G      1.758         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 19.2it/s 0.3s
                   all      0.345      0.873

      Epoch    GPU_mem       loss  Instances       Size
      10/50     0.928G      1.741         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 24.3it/s 0.2s
                   all      0.335      0.891

      Epoch    GPU_mem       loss  Instances       Size
      11/50      0.93G      1.714         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 23.5it/s 0.2s
                   all      0.352      0.884

      Epoch    GPU_mem       loss  Instances       Size
      12/50     0.936G       1.73         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 12.5it/s 0.4s
                   all      0.271       0.87

      Epoch    GPU_mem       loss  Instances       Size
      13/50     0.941G      1.702         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.6it/s 0.2s
                   all      0.331      0.901

      Epoch    GPU_mem       loss  Instances       Size
      14/50     0.941G      1.684         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 15.7it/s 0.3s
                   all      0.292      0.901

      Epoch    GPU_mem       loss  Instances       Size
      15/50     0.941G      1.688         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 17.1it/s 0.3s
                   all      0.282       0.88

      Epoch    GPU_mem       loss  Instances       Size
      16/50     0.941G      1.699         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.8it/s 0.2s
                   all      0.394      0.891

      Epoch    GPU_mem       loss  Instances       Size
      17/50     0.941G      1.683         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 17.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 20.4it/s 0.2s
                   all      0.387      0.919

      Epoch    GPU_mem       loss  Instances       Size
      18/50     0.941G      1.684         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 18.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 22.2it/s 0.2s
                   all      0.384      0.937

      Epoch    GPU_mem       loss  Instances       Size
      19/50     0.941G      1.663         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 17.0it/s 0.3s
                   all      0.405      0.923

      Epoch    GPU_mem       loss  Instances       Size
      20/50     0.941G      1.684         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 18.8it/s 0.3s
                   all       0.38      0.908

      Epoch    GPU_mem       loss  Instances       Size
      21/50     0.941G       1.63         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 18.5it/s 0.3s
                   all      0.394      0.905

      Epoch    GPU_mem       loss  Instances       Size
      22/50     0.941G      1.643         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 20.3it/s 0.2s
                   all      0.423      0.912

      Epoch    GPU_mem       loss  Instances       Size
      23/50     0.941G      1.648         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 17.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 16.4it/s 0.3s
                   all      0.444      0.915

      Epoch    GPU_mem       loss  Instances       Size
      24/50     0.941G      1.588         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 25.9it/s 0.2s
                   all      0.454      0.944

      Epoch    GPU_mem       loss  Instances       Size
      25/50     0.941G      1.617         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 19.5it/s 0.3s
                   all      0.479      0.944

      Epoch    GPU_mem       loss  Instances       Size
      26/50     0.941G      1.607         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 19.1it/s 0.3s
                   all      0.458      0.926

      Epoch    GPU_mem       loss  Instances       Size
      27/50     0.941G      1.598         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 17.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 22.1it/s 0.2s
                   all      0.482      0.912

      Epoch    GPU_mem       loss  Instances       Size
      28/50     0.945G      1.558         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 18.4it/s 0.3s
                   all      0.468       0.93

      Epoch    GPU_mem       loss  Instances       Size
      29/50     0.945G      1.556         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.6it/s 0.2s
                   all      0.475      0.926

      Epoch    GPU_mem       loss  Instances       Size
      30/50     0.955G      1.549         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 19.3it/s 0.3s
                   all      0.486      0.944

      Epoch    GPU_mem       loss  Instances       Size
      31/50     0.955G      1.573         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 13.7it/s 0.4s
                   all      0.461      0.947

      Epoch    GPU_mem       loss  Instances       Size
      32/50     0.965G      1.552         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 18.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 20.4it/s 0.2s
                   all      0.482      0.944

      Epoch    GPU_mem       loss  Instances       Size
      33/50     0.965G      1.548         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 19.7it/s 0.3s
                   all      0.518      0.933

      Epoch    GPU_mem       loss  Instances       Size
      34/50     0.975G      1.522         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 9.5it/s 0.5s
                   all      0.489       0.94

      Epoch    GPU_mem       loss  Instances       Size
      35/50     0.975G      1.525         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.6it/s 0.2s
                   all      0.468      0.944

      Epoch    GPU_mem       loss  Instances       Size
      36/50     0.975G      1.526         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 22.6it/s 0.2s
                   all      0.489      0.958

      Epoch    GPU_mem       loss  Instances       Size
      37/50     0.975G      1.516         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 9.6it/s 0.5s
                   all      0.472      0.947

      Epoch    GPU_mem       loss  Instances       Size
      38/50     0.975G      1.539         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 17.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 15.9it/s 0.3s
                   all      0.465      0.954

      Epoch    GPU_mem       loss  Instances       Size
      39/50     0.975G      1.491         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 17.5it/s 0.3s
                   all      0.535      0.951

      Epoch    GPU_mem       loss  Instances       Size
      40/50     0.975G      1.481         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 17.6it/s 0.3s
                   all      0.528      0.954

      Epoch    GPU_mem       loss  Instances       Size
      41/50     0.975G      1.477         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 26.5it/s 0.2s
                   all      0.518      0.958

      Epoch    GPU_mem       loss  Instances       Size
      42/50     0.975G      1.477         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 19.5it/s 0.3s
                   all      0.521      0.958

      Epoch    GPU_mem       loss  Instances       Size
      43/50     0.975G      1.459         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.2it/s 0.2s
                   all      0.489      0.961

      Epoch    GPU_mem       loss  Instances       Size
      44/50     0.975G      1.484         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 15.4it/s 0.3s
                   all      0.489      0.965

      Epoch    GPU_mem       loss  Instances       Size
      45/50     0.975G      1.418         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 20.1it/s 0.2s
                   all      0.486      0.954

      Epoch    GPU_mem       loss  Instances       Size
      46/50     0.975G      1.449         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 17.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.8it/s 0.2s
                   all      0.493      0.954

      Epoch    GPU_mem       loss  Instances       Size
      47/50     0.975G      1.447         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 13.3it/s 0.4s
                   all      0.518      0.954

      Epoch    GPU_mem       loss  Instances       Size
      48/50     0.975G      1.454         27        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 17.6it/s 0.3s
                   all      0.528      0.947

      Epoch    GPU_mem       loss  Instances       Size
      49/50     0.975G      1.452         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 13.1it/s 0.4s
                   all      0.514      0.954

      Epoch    GPU_mem       loss  Instances       Size
      50/50     0.975G       1.43         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 11.4it/s 0.4s
                   all      0.518      0.961

50 epochs completed in 0.269 hours.
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls3/weights/last.pt, 3.6MB
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls3/weights/best.pt, 3.6MB

Validating /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls3/weights/best.pt...
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
YOLO12-cls-mmoutu summary (fused): 94 layers, 1,718,607 parameters, 0 gradients, 3.5 GFLOPs
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 988 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 284 images in 7 classes ✅
test: /content/drive/MyDrive/MMOTU_splits_full/test... found 144 images in 7 classes ✅
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 5.7it/s 0.9s
                   all      0.535      0.951
Speed: 0.1ms preprocess, 0.7ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls3

ultralytics.utils.metrics.ClassifyMetrics object with attributes:

confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f130200c950>
curves: []
curves_results: []
fitness: 0.74295774102211
keys: ['metrics/accuracy_top1', 'metrics/accuracy_top5']
results_dict: {'metrics/accuracy_top1': 0.5352112650871277, 'metrics/accuracy_top5': 0.9507042169570923, 'fitness': 0.74295774102211}
save_dir: PosixPath('/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls3')
speed: {'preprocess': 0.07345394014535, 'inference': 0.7217223873288877, 'loss': 0.00023272535362990875, 'postprocess': 0.0004092676071720657}
task: 'classify'
top1: 0.5352112650871277
top5: 0.9507042169570923

In [ ]:
project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS"
name="yolov12_cls"

In [ ]:
import pandas as pd

csv_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/results.csv"
df = pd.read_csv(csv_path)

# Show last epoch (final performance)
df.tail(1)

,epoch,time,train/loss,metrics/accuracy_top1,metrics/accuracy_top5,val/loss,lr/pg0,lr/pg1,lr/pg2
2,3,60.0409,1.87482,0.19366,0.86972,2.85195,0.000803,0.000803,0.000803

In [ ]:
from sklearn.metrics import classification_report

y_true = []
y_pred = []

# Assuming CLASS_MAP is available from previous cells.
# class_names_list and class_to_idx will be derived from CLASS_MAP.
class_names_list = list(CLASS_MAP.values())
class_to_idx = {name: i for i, name in enumerate(class_names_list)}

for r in results:
    y_pred.append(r.probs.top1) # Get the top1 predicted class index
    # Extract the true class label from the image path
    # The path structure is /content/MMOTU_splits_full/test/CLASS_NAME/image.jpg
    y_true.append(os.path.basename(os.path.dirname(r.path)))

# Convert true class names to indices for classification_report
y_true_idx = [class_to_idx[c] for c in y_true]

# Generate and print the classification report
report = classification_report(y_true_idx, y_pred, target_names=class_names_list)
print(report)

                      precision    recall  f1-score   support

        Normal_Ovary       0.03      0.03      0.03        34
         Simple_Cyst       0.12      0.05      0.07        22
            Teratoma       0.00      0.00      0.00        34
  Serous_Cystadenoma       0.58      0.78      0.67         9
Mucinous_Cystadenoma       0.00      0.00      0.00         7
      Chocolate_Cyst       0.03      0.04      0.03        27
    Theca_Cell_Tumor       0.83      0.91      0.87        11

            accuracy                           0.14       144
           macro avg       0.23      0.26      0.24       144
        weighted avg       0.13      0.14      0.13       144

In [ ]:
import pandas as pd

results_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls/results.csv"
df = pd.read_csv(results_path)

# Show last epoch results (final model)

df.tail(1)

,epoch,time,train/loss,metrics/accuracy_top1,metrics/accuracy_top5,val/loss,lr/pg0,lr/pg1,lr/pg2
49,50,4438.68,0.1633,0.7489,0.98018,1.16996,0.000027,0.000027,0.000027

In [ ]:
!find /usr/local/lib/python3.12/dist-packages/ultralytics -path "*v12*" -name "yolov12s.yaml"

In [ ]:
!ls /usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models

11  12	rt-detr  v10  v3  v5  v6  v8  v9

In [ ]:
!ls /usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models/v12

ls: cannot access '/usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models/v12': No such file or directory

In [ ]:
!git clone https://github.com/ultralytics/ultralytics.git

fatal: destination path 'ultralytics' already exists and is not an empty directory.

In [ ]:
model = YOLO("ultralytics/ultralytics/cfg/models/12/yolo12-cls.yaml")

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls summary: 152 layers, 1,820,976 parameters, 1,820,976 gradients, 3.7 GFLOPs

In [ ]:
yaml_content = """
# YOLO12-cls image classification model

nc: 7

scales:
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024]
  m: [0.50, 1.00, 512]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.50, 512]

backbone:
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [-1, 4, A2C2f, [512, True, 4]]
  - [-1, 1, Conv, [1024, 3, 2]]
  - [-1, 4, A2C2f, [1024, True, 1]]

head:
  - [-1, 1, Classify, [nc]]
"""

with open("/content/yolo12-cls-mmoutu.yaml", "w") as f:
    f.write(yaml_content)

print("YAML file created successfully")

YAML file created successfully

In [ ]:
import os
print(os.path.exists("/content/yolo12-cls-mmoutu.yaml"))

True

In [ ]:
from ultralytics import YOLO

model = YOLO("/content/yolo12-cls-mmoutu.yaml")

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs

In [ ]:
from ultralytics import YOLO

DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

# Load YOLOv12 classification model (YAML, no pretrained .pt exists yet)
model_v12 = YOLO("/content/yolo12-cls-mmoutu.yaml")

model_v12.train(
    data=DATA_PATH,
    epochs=50,              # SAME as YOLOv8 & YOLOv11
    imgsz=224,              # Classification standard
    batch=32,

    project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS",
    name="yolov12_cls",

    # SAME augmentation as YOLOv11 (fair comparison)
    fliplr=0.5,
    flipud=0.3,
    degrees=10,
    translate=0.1,
    scale=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4
)

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/MMOTU_splits_full, degrees=10, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.3, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/content/yolo12-cls-mmoutu.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov12_cls, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/YOLO_MMOTU_RESULTS, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 962 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 454 images in 7 classes ✅
WARNING ⚠️ test: /content/drive/MyDrive/MMOTU_splits_full/test... found 0 images in 0 classes (no images found)
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1    339207  ultralytics.nn.modules.head.Classify         [256, 7]
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs
train: Fast image access ✅ (ping: 0.5±0.1 ms, read: 36.6±25.4 MB/s, size: 103.2 KB)
train: Scanning /content/drive/MyDrive/MMOTU_splits_full/train... 962 images, 0 corrupt: 100% ━━━━━━━━━━━━ 962/962 203.5Kit/s 0.0s
val: Fast image access ✅ (ping: 0.7±0.2 ms, read: 20.7±5.7 MB/s, size: 80.4 KB)
val: Scanning /content/drive/MyDrive/MMOTU_splits_full/val... 454 images, 0 corrupt: 100% ━━━━━━━━━━━━ 454/454 437.8Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 58 weight(decay=0.0), 59 weight(decay=0.0005), 59 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 0 dataloader workers
Logging results to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/50         0G      1.927          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:36
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all      0.192       0.89

      Epoch    GPU_mem       loss  Instances       Size
       2/50         0G      1.856          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:37
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.8s
                   all      0.214      0.866

      Epoch    GPU_mem       loss  Instances       Size
       3/50         0G      1.904          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.7s
                   all      0.262      0.868

      Epoch    GPU_mem       loss  Instances       Size
       4/50         0G      1.891          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.9s
                   all      0.225      0.874

      Epoch    GPU_mem       loss  Instances       Size
       5/50         0G      1.838          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:36
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.0s
                   all      0.284      0.888

      Epoch    GPU_mem       loss  Instances       Size
       6/50         0G      1.758          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.4s
                   all      0.284      0.848

      Epoch    GPU_mem       loss  Instances       Size
       7/50         0G       1.79          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.6s
                   all      0.273      0.894

      Epoch    GPU_mem       loss  Instances       Size
       8/50         0G       1.75          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.4s
                   all      0.315      0.892

      Epoch    GPU_mem       loss  Instances       Size
       9/50         0G      1.798          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.3s
                   all      0.289      0.912

      Epoch    GPU_mem       loss  Instances       Size
      10/50         0G      1.738          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.295      0.892

      Epoch    GPU_mem       loss  Instances       Size
      11/50         0G      1.772          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:33
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.3s
                   all      0.326      0.903

      Epoch    GPU_mem       loss  Instances       Size
      12/50         0G      1.717          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.6s
                   all      0.304       0.91

      Epoch    GPU_mem       loss  Instances       Size
      13/50         0G       1.78          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.317      0.901

      Epoch    GPU_mem       loss  Instances       Size
      14/50         0G      1.751          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.328      0.905

      Epoch    GPU_mem       loss  Instances       Size
      15/50         0G      1.767          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.6s
                   all      0.322       0.91

      Epoch    GPU_mem       loss  Instances       Size
      16/50         0G      1.737          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all       0.33      0.919

      Epoch    GPU_mem       loss  Instances       Size
      17/50         0G      1.721          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.9s
                   all      0.326      0.901

      Epoch    GPU_mem       loss  Instances       Size
      18/50         0G      1.697          2        224: 100% ━━━━━━━━━━━━ 31/31 3.2s/it 1:38
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.8s
                   all      0.333      0.914

      Epoch    GPU_mem       loss  Instances       Size
      19/50         0G      1.703          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.6s
                   all      0.324      0.919

      Epoch    GPU_mem       loss  Instances       Size
      20/50         0G      1.726          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.9s
                   all      0.372      0.914

      Epoch    GPU_mem       loss  Instances       Size
      21/50         0G       1.73          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.1s
                   all      0.361      0.905

      Epoch    GPU_mem       loss  Instances       Size
      22/50         0G      1.667          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all       0.35      0.894

      Epoch    GPU_mem       loss  Instances       Size
      23/50         0G      1.701          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all      0.399      0.916

      Epoch    GPU_mem       loss  Instances       Size
      24/50         0G      1.704          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.7s
                   all      0.379       0.91

      Epoch    GPU_mem       loss  Instances       Size
      25/50         0G      1.714          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 18.0s
                   all      0.381      0.903

      Epoch    GPU_mem       loss  Instances       Size
      26/50         0G      1.662          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.3s
                   all      0.405      0.923

      Epoch    GPU_mem       loss  Instances       Size
      27/50         0G      1.694          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 18.0s
                   all      0.374      0.923

      Epoch    GPU_mem       loss  Instances       Size
      28/50         0G       1.67          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.416      0.927

      Epoch    GPU_mem       loss  Instances       Size
      29/50         0G      1.644          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.385      0.925

      Epoch    GPU_mem       loss  Instances       Size
      30/50         0G       1.67          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:36
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.352      0.914

      Epoch    GPU_mem       loss  Instances       Size
      31/50         0G      1.646          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.1s
                   all      0.432      0.932

      Epoch    GPU_mem       loss  Instances       Size
      32/50         0G       1.64          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.4s
                   all      0.423      0.934

      Epoch    GPU_mem       loss  Instances       Size
      33/50         0G      1.604          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:33
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.1s
                   all      0.423      0.923

      Epoch    GPU_mem       loss  Instances       Size
      34/50         0G      1.631          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:33
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.9s
                   all       0.46      0.945

      Epoch    GPU_mem       loss  Instances       Size
      35/50         0G      1.609          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.1s
                   all       0.43      0.921

      Epoch    GPU_mem       loss  Instances       Size
      36/50         0G      1.611          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 18.0s
                   all      0.441      0.932

      Epoch    GPU_mem       loss  Instances       Size
      37/50         0G      1.591          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.8s
                   all      0.474      0.927

      Epoch    GPU_mem       loss  Instances       Size
      38/50         0G      1.584          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.0s
                   all      0.447      0.905

      Epoch    GPU_mem       loss  Instances       Size
      39/50         0G      1.548          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.8s
                   all      0.493      0.916

      Epoch    GPU_mem       loss  Instances       Size
      40/50         0G      1.557          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.478      0.912

      Epoch    GPU_mem       loss  Instances       Size
      41/50         0G      1.566          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:33
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.7s
                   all       0.48      0.932

      Epoch    GPU_mem       loss  Instances       Size
      42/50         0G      1.556          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.5s
                   all       0.48       0.93

      Epoch    GPU_mem       loss  Instances       Size
      43/50         0G      1.514          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.4s
                   all      0.482      0.934

      Epoch    GPU_mem       loss  Instances       Size
      44/50         0G      1.512          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.4s
                   all      0.493      0.921

      Epoch    GPU_mem       loss  Instances       Size
      45/50         0G      1.486          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.3s
                   all      0.496      0.925

      Epoch    GPU_mem       loss  Instances       Size
      46/50         0G      1.507          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.3s
                   all      0.509       0.93

      Epoch    GPU_mem       loss  Instances       Size
      47/50         0G      1.519          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:37
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.3s
                   all      0.498      0.936

      Epoch    GPU_mem       loss  Instances       Size
      48/50         0G        1.5          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.6s
                   all      0.509      0.934

      Epoch    GPU_mem       loss  Instances       Size
      49/50         0G      1.464          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.4s
                   all      0.513      0.936

      Epoch    GPU_mem       loss  Instances       Size
      50/50         0G      1.485          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.4s
                   all      0.513      0.934

50 epochs completed in 1.568 hours.
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/last.pt, 3.6MB
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/best.pt, 3.6MB

Validating /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/best.pt...
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
YOLO12-cls-mmoutu summary (fused): 94 layers, 1,718,607 parameters, 0 gradients, 3.5 GFLOPs
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 962 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 454 images in 7 classes ✅
WARNING ⚠️ test: /content/drive/MyDrive/MMOTU_splits_full/test... found 0 images in 0 classes (no images found)
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all      0.513      0.934
Speed: 0.0ms preprocess, 20.1ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls

ultralytics.utils.metrics.ClassifyMetrics object with attributes:

confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7ec3babb78c0>
curves: []
curves_results: []
fitness: 0.7235682606697083
keys: ['metrics/accuracy_top1', 'metrics/accuracy_top5']
results_dict: {'metrics/accuracy_top1': 0.5132158398628235, 'metrics/accuracy_top5': 0.933920681476593, 'fitness': 0.7235682606697083}
save_dir: PosixPath('/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls')
speed: {'preprocess': 0.0006485660887366398, 'inference': 20.061874947153463, 'loss': 3.434360972995406e-05, 'postprocess': 8.425993230993888e-05}
task: 'classify'
top1: 0.5132158398628235
top5: 0.933920681476593

In [ ]:
project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS"
name="yolov12_cls"

In [ ]:
import pandas as pd

csv_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/results.csv"
df = pd.read_csv(csv_path)

# Show last epoch (final performance)
df.tail(1)

,epoch,time,train/loss,metrics/accuracy_top1,metrics/accuracy_top5,val/loss,lr/pg0,lr/pg1,lr/pg2
49,50,5643.21,1.48538,0.51322,0.93392,1.44068,0.000027,0.000027,0.000027

# Task
Re-train and re-evaluate the YOLOv11 and YOLOv12 classification models, ensuring proper data splitting and exclusion of class 7, and provide their accurate performance metrics.

## Clean up previous split directories

### Subtask:
Remove any existing 'MMOTU_splits_full' directory from '/content/drive/MyDrive/' to ensure a clean slate for data splitting.

**Reasoning**:
To ensure a clean slate for data splitting, I need to remove the existing directory '/content/drive/MyDrive/MMOTU_splits_full' and all its contents.

In [ ]:
import shutil
import os

dir_to_remove = "/content/drive/MyDrive/MMOTU_splits_full"

if os.path.exists(dir_to_remove):
    shutil.rmtree(dir_to_remove)
    print(f"Removed existing directory: {dir_to_remove}")
else:
    print(f"Directory not found, no need to remove: {dir_to_remove}")

Removed existing directory: /content/drive/MyDrive/MMOTU_splits_full

# Task
Create new split directories and copy images for train, val, and test sets to "/content/drive/MyDrive/MMOTU_splits_full", ensuring class 7 is excluded.

## Create new split directories

### Subtask:
Recreate the 'train', 'val', and 'test' directories under the corrected 'OUTPUT_ROOT' in Google Drive.

**Reasoning**:
I need to recreate the directory structure for the data splits as specified in the instructions. This involves iterating through the splits (train, val, test) and each class name, then creating the corresponding directories using `os.makedirs` with `exist_ok=True` to avoid errors if directories already exist.

In [ ]:
for split in splits:
    for cls_name in CLASS_MAP.values():
        os.makedirs(os.path.join(OUTPUT_ROOT, split, cls_name), exist_ok=True)

## Perform data splitting and copying

### Subtask:
Re-execute the code responsible for splitting the dataset and copying images into the newly created 'train', 'val', and 'test' directories in Google Drive.

**Reasoning**:
To perform data splitting and copying, I need to re-execute the code that iterates through each class, splits the images into train, validation, and test sets using the specified ratios, and then copies them to their respective directories.

In [ ]:
for cls_name in CLASS_MAP.values():
    images = class_images[cls_name]

    # Split data into train, val, test
    train_imgs, temp_imgs = train_test_split(images, train_size=train_ratio, random_state=42)
    val_imgs, test_imgs = train_test_split(temp_imgs, test_size=test_ratio/(val_ratio + test_ratio), random_state=42)

    # Copy images to respective directories
    for img_path in tqdm(train_imgs, desc=f"Copying {cls_name} train images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "train", cls_name, os.path.basename(img_path)))
    for img_path in tqdm(val_imgs, desc=f"Copying {cls_name} val images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "val", cls_name, os.path.basename(img_path)))
    for img_path in tqdm(test_imgs, desc=f"Copying {cls_name} test images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "test", cls_name, os.path.basename(img_path)))

Copying Normal_Ovary train images: 100%|██████████| 235/235 [00:03<00:00, 72.67it/s]
Copying Normal_Ovary val images: 100%|██████████| 67/67 [00:00<00:00, 101.54it/s]
Copying Normal_Ovary test images: 100%|██████████| 34/34 [00:00<00:00, 100.60it/s]
Copying Simple_Cyst train images: 100%|██████████| 153/153 [00:01<00:00, 90.37it/s]
Copying Simple_Cyst val images: 100%|██████████| 44/44 [00:00<00:00, 97.00it/s]
Copying Simple_Cyst test images: 100%|██████████| 22/22 [00:00<00:00, 113.36it/s]
Copying Teratoma train images: 100%|██████████| 235/235 [00:02<00:00, 98.23it/s]
Copying Teratoma val images: 100%|██████████| 67/67 [00:00<00:00, 93.74it/s]
Copying Teratoma test images: 100%|██████████| 34/34 [00:00<00:00, 60.97it/s]
Copying Serous_Cystadenoma train images: 100%|██████████| 61/61 [00:00<00:00, 74.32it/s]
Copying Serous_Cystadenoma val images: 100%|██████████| 18/18 [00:00<00:00, 104.67it/s]
Copying Serous_Cystadenoma test images: 100%|██████████| 9/9 [00:00<00:00, 109.23it/s]
Copying Mucinous_Cystadenoma train images: 100%|██████████| 46/46 [00:00<00:00, 76.72it/s]
Copying Mucinous_Cystadenoma val images: 100%|██████████| 13/13 [00:00<00:00, 57.12it/s]
Copying Mucinous_Cystadenoma test images: 100%|██████████| 7/7 [00:00<00:00, 65.49it/s]
Copying Chocolate_Cyst train images: 100%|██████████| 186/186 [00:01<00:00, 96.37it/s]
Copying Chocolate_Cyst val images: 100%|██████████| 54/54 [00:00<00:00, 94.97it/s]
Copying Chocolate_Cyst test images: 100%|██████████| 27/27 [00:00<00:00, 102.16it/s]
Copying Theca_Cell_Tumor train images: 100%|██████████| 72/72 [00:00<00:00, 78.20it/s]
Copying Theca_Cell_Tumor val images: 100%|██████████| 21/21 [00:00<00:00, 97.27it/s]
Copying Theca_Cell_Tumor test images: 100%|██████████| 11/11 [00:00<00:00, 113.08it/s]

**Reasoning**:
The previous execution of the data splitting and copying process completed successfully, indicated by the tqdm progress bars for all classes. To fulfill the instruction to re-execute this process for the newly created directories, I will run the same code again.

In [ ]:
for cls_name in CLASS_MAP.values():
    images = class_images[cls_name]

    # Split data into train, val, test
    train_imgs, temp_imgs = train_test_split(images, train_size=train_ratio, random_state=42)
    val_imgs, test_imgs = train_test_split(temp_imgs, test_size=test_ratio/(val_ratio + test_ratio), random_state=42)

    # Copy images to respective directories
    for img_path in tqdm(train_imgs, desc=f"Copying {cls_name} train images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "train", cls_name, os.path.basename(img_path)))
    for img_path in tqdm(val_imgs, desc=f"Copying {cls_name} val images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "val", cls_name, os.path.basename(img_path)))
    for img_path in tqdm(test_imgs, desc=f"Copying {cls_name} test images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "test", cls_name, os.path.basename(img_path)))

Copying Normal_Ovary train images: 100%|██████████| 235/235 [00:03<00:00, 62.69it/s]
Copying Normal_Ovary val images: 100%|██████████| 67/67 [00:00<00:00, 89.47it/s]
Copying Normal_Ovary test images: 100%|██████████| 34/34 [00:00<00:00, 80.06it/s]
Copying Simple_Cyst train images: 100%|██████████| 153/153 [00:02<00:00, 72.93it/s]
Copying Simple_Cyst val images: 100%|██████████| 44/44 [00:00<00:00, 89.59it/s]
Copying Simple_Cyst test images: 100%|██████████| 22/22 [00:00<00:00, 61.46it/s]
Copying Teratoma train images: 100%|██████████| 235/235 [00:02<00:00, 86.92it/s]
Copying Teratoma val images: 100%|██████████| 67/67 [00:00<00:00, 77.74it/s]
Copying Teratoma test images: 100%|██████████| 34/34 [00:00<00:00, 79.90it/s]
Copying Serous_Cystadenoma train images: 100%|██████████| 61/61 [00:00<00:00, 81.63it/s]
Copying Serous_Cystadenoma val images: 100%|██████████| 18/18 [00:00<00:00, 77.73it/s]
Copying Serous_Cystadenoma test images: 100%|██████████| 9/9 [00:00<00:00, 46.73it/s]
Copying Mucinous_Cystadenoma train images:  13%|█▎        | 6/46 [00:00<00:02, 19.68it/s]

KeyboardInterrupt:

# Task
Verify the image counts in each split (train, val, test) within `/content/drive/MyDrive/MMOTU_splits_full` to ensure they match the expected distribution for each class, after excluding class 7.

## Verify image counts

### Subtask:
Confirm that the number of images in each split (train, val, test) within 'OUTPUT_ROOT' matches the expected counts (total of 1416 images after excluding class 7).

**Reasoning**:
To confirm the image counts in each split and class, I need to iterate through the directory structure and count the files, storing them in a dictionary, then print the aggregated results to verify the total count and class-wise distribution.

In [ ]:
import os
from collections import defaultdict

split_counts = defaultdict(lambda: defaultdict(int))

print("Verifying image counts...")

for split in splits:
    for cls_name in CLASS_MAP.values():
        cls_path = os.path.join(OUTPUT_ROOT, split, cls_name)
        if os.path.exists(cls_path):
            # Count only image files (e.g., .jpg, .png)
            image_files = [f for f in os.listdir(cls_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
            count = len(image_files)
            split_counts[split][cls_name] = count

print("\nImage counts per split and class:")
for split, classes in split_counts.items():
    print(f"  {split.capitalize()} set:")
    for cls_name, count in classes.items():
        print(f"    {cls_name}: {count} images")

total_images_per_class = defaultdict(int)
overall_total_images = 0

print("\nTotal images per class across all splits:")
for split, classes in split_counts.items():
    for cls_name, count in classes.items():
        total_images_per_class[cls_name] += count
        overall_total_images += count

for cls_name, total_count in total_images_per_class.items():
    print(f"  {cls_name}: {total_count} images")

print(f"\nOverall total images: {overall_total_images}")

# Expected total (excluding class 7: 1598 - 182 = 1416)
# This value should be consistent with the original count of all_data (1416) if the split ratios were applied perfectly.
# Let's verify against all_data length first.
expected_total_from_all_data = len(all_data)
print(f"Expected total images from original filtered data (all_data): {expected_total_from_all_data}")

if overall_total_images == expected_total_from_all_data:
    print("\nVerification successful: Total images match expected count!")
else:
    print(f"\nVerification failed: Total images ({overall_total_images}) do not match expected count ({expected_total_from_all_data}).")

Verifying image counts...

Image counts per split and class:
  Train set:
    Normal_Ovary: 235 images
    Simple_Cyst: 153 images
    Teratoma: 235 images
    Serous_Cystadenoma: 61 images
    Mucinous_Cystadenoma: 46 images
    Chocolate_Cyst: 186 images
    Theca_Cell_Tumor: 72 images
  Val set:
    Normal_Ovary: 67 images
    Simple_Cyst: 44 images
    Teratoma: 67 images
    Serous_Cystadenoma: 18 images
    Mucinous_Cystadenoma: 13 images
    Chocolate_Cyst: 54 images
    Theca_Cell_Tumor: 21 images
  Test set:
    Normal_Ovary: 34 images
    Simple_Cyst: 22 images
    Teratoma: 34 images
    Serous_Cystadenoma: 9 images
    Mucinous_Cystadenoma: 7 images
    Chocolate_Cyst: 27 images
    Theca_Cell_Tumor: 11 images

Total images per class across all splits:
  Normal_Ovary: 336 images
  Simple_Cyst: 219 images
  Teratoma: 336 images
  Serous_Cystadenoma: 88 images
  Mucinous_Cystadenoma: 66 images
  Chocolate_Cyst: 267 images
  Theca_Cell_Tumor: 104 images

Overall total images: 1416
Expected total images from original filtered data (all_data): 1416

Verification successful: Total images match expected count!

## Re-run YOLOv11 model training

### Subtask:
Re-train the YOLOv11 classification model using the correctly prepared dataset.

**Reasoning**:
I need to initialize the YOLOv11 model with pretrained weights and then start the training process with the specified parameters for epochs, image size, batch size, project/name, and augmentation settings.

# Task
Okay, I understand. It looks like the training for the YOLOv11 model was interrupted. I will restart the training for the YOLOv11 classification model now.

## Re-run YOLOv11 model training

### Subtask:
Re-train the YOLOv11 classification model using the correctly prepared dataset.

### Reasoning:
The previous execution of the YOLOv11 training was interrupted. I need to re-execute the training cell to ensure the model is fully trained for 50 epochs with the specified parameters and augmentations, so that its performance can be properly evaluated in the subsequent steps.

## Re-train YOLOv11 classification model

### Subtask:
Re-train the YOLOv11 classification model using the correctly prepared dataset.

**Reasoning**:
The previous attempt to train the YOLOv11 model was interrupted. I need to re-execute the code cell that initializes the YOLOv11 model and starts training with the specified parameters to complete the subtask.

# Task
The YOLOv11 classification model training was interrupted. I will restart the training to complete the task.

Execute the following cell to train the YOLOv11 classification model:
```python
from ultralytics import YOLO

DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

model_v11 = YOLO("yolo11n-cls.pt")

model_v11.train(
    data=DATA_PATH,
    epochs=50,
    imgsz=224,
    batch=32,

    project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS",
    name="yolov11_cls",

    fliplr=0.5,
    flipud=0.3,
    degrees=10,
    translate=0.1,
    scale=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4
)
```

## Re-run YOLOv11 model training

### Subtask:
Re-train the YOLOv11 classification model using the correctly prepared dataset.

**Reasoning**:
The user explicitly asked to execute the code in cell `a7597753` to restart the training of the YOLOv11 classification model. I will use the `code_block` command to re-execute this cell.

In [ ]:
from ultralytics import YOLO

DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

model_v11 = YOLO("yolo11n-cls.pt")

model_v11.train(
    data=DATA_PATH,
    epochs=50,
    imgsz=224,
    batch=32,

    project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS",
    name="yolov11_cls",

    fliplr=0.5,
    flipud=0.3,
    degrees=10,
    translate=0.1,
    scale=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4
)

Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/MMOTU_splits_full, degrees=10, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.3, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n-cls.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov11_cls5, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/YOLO_MMOTU_RESULTS, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 988 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 284 images in 7 classes ✅
test: /content/drive/MyDrive/MMOTU_splits_full/test... found 144 images in 7 classes ✅
Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 10                  -1  1    339207  ultralytics.nn.modules.head.Classify         [256, 7]
YOLO11n-cls summary: 86 layers, 1,540,071 parameters, 1,540,071 gradients, 3.3 GFLOPs
Transferred 234/236 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.4±0.2 ms, read: 57.4±22.0 MB/s, size: 86.8 KB)
train: Scanning /content/drive/MyDrive/MMOTU_splits_full/train... 987 images, 1 corrupt: 100% ━━━━━━━━━━━━ 987/987 1.4Mit/s 0.0s
train: /content/drive/MyDrive/MMOTU_splits_full/train/Mucinous_Cystadenoma/600.JPG: ignoring corrupt image/label: cannot identify image file '/content/drive/MyDrive/MMOTU_splits_full/train/Mucinous_Cystadenoma/600.JPG'
val: Fast image access ✅ (ping: 1.2±1.0 ms, read: 22.2±6.7 MB/s, size: 88.8 KB)
val: Scanning /content/drive/MyDrive/MMOTU_splits_full/val... 284 images, 0 corrupt: 100% ━━━━━━━━━━━━ 284/284 169.7Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 39 weight(decay=0.0), 40 weight(decay=0.0005), 40 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/50     0.621G      1.845         27        224: 100% ━━━━━━━━━━━━ 31/31 1.5it/s 20.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 38.4it/s 0.1s
                   all      0.468      0.884

      Epoch    GPU_mem       loss  Instances       Size
       2/50     0.621G      1.474         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 43.8it/s 0.1s
                   all      0.599      0.954

      Epoch    GPU_mem       loss  Instances       Size
       3/50     0.621G      1.293         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 27.1it/s 0.2s
                   all      0.511      0.951

      Epoch    GPU_mem       loss  Instances       Size
       4/50     0.621G      1.268         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.9it/s 0.2s
                   all      0.489      0.958

      Epoch    GPU_mem       loss  Instances       Size
       5/50     0.621G      1.197         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 22.6it/s 0.2s
                   all      0.556      0.944

      Epoch    GPU_mem       loss  Instances       Size
       6/50     0.621G      1.114         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 35.4it/s 0.1s
                   all      0.613      0.965

      Epoch    GPU_mem       loss  Instances       Size
       7/50     0.621G     0.9648         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 33.3it/s 0.2s
                   all      0.623      0.965

      Epoch    GPU_mem       loss  Instances       Size
       8/50     0.621G     0.8694         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 37.1it/s 0.1s
                   all      0.623      0.975

      Epoch    GPU_mem       loss  Instances       Size
       9/50     0.621G     0.8552         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 40.0it/s 0.1s
                   all      0.658      0.975

      Epoch    GPU_mem       loss  Instances       Size
      10/50     0.621G     0.7622         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 35.0it/s 0.1s
                   all      0.658      0.979

      Epoch    GPU_mem       loss  Instances       Size
      11/50     0.621G     0.7836         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 32.1it/s 0.2s
                   all      0.655      0.982

      Epoch    GPU_mem       loss  Instances       Size
      12/50     0.621G     0.7648         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 31.9it/s 0.2s
                   all      0.683      0.975

      Epoch    GPU_mem       loss  Instances       Size
      13/50     0.621G     0.6933         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 30.6it/s 0.2s
                   all      0.676      0.986

      Epoch    GPU_mem       loss  Instances       Size
      14/50     0.621G      0.658         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 32.0it/s 0.2s
                   all      0.669      0.993

      Epoch    GPU_mem       loss  Instances       Size
      15/50     0.621G     0.5985         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 31.9it/s 0.2s
                   all       0.68      0.989

      Epoch    GPU_mem       loss  Instances       Size
      16/50     0.621G     0.4681         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 39.9it/s 0.1s
                   all      0.704      0.989

      Epoch    GPU_mem       loss  Instances       Size
      17/50     0.621G     0.5214         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 33.7it/s 0.1s
                   all      0.711      0.989

      Epoch    GPU_mem       loss  Instances       Size
      18/50     0.621G     0.4716         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 31.6it/s 0.2s
                   all      0.746      0.986

      Epoch    GPU_mem       loss  Instances       Size
      19/50     0.621G     0.4658         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 18.5it/s 0.3s
                   all      0.725      0.986

      Epoch    GPU_mem       loss  Instances       Size
      20/50     0.621G     0.4673         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 22.2it/s 0.2s
                   all      0.708      0.975

      Epoch    GPU_mem       loss  Instances       Size
      21/50     0.621G     0.4203         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 25.4it/s 0.2s
                   all      0.725      0.989

      Epoch    GPU_mem       loss  Instances       Size
      22/50     0.621G     0.4186         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 28.4it/s 0.2s
                   all      0.729      0.989

      Epoch    GPU_mem       loss  Instances       Size
      23/50     0.621G     0.3731         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 36.2it/s 0.1s
                   all      0.725      0.989

      Epoch    GPU_mem       loss  Instances       Size
      24/50     0.621G     0.3557         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.1it/s 0.2s
                   all      0.715      0.993

      Epoch    GPU_mem       loss  Instances       Size
      25/50     0.621G     0.4006         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 33.8it/s 0.1s
                   all      0.725      0.996

      Epoch    GPU_mem       loss  Instances       Size
      26/50     0.621G     0.3766         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 36.4it/s 0.1s
                   all      0.662      0.989

      Epoch    GPU_mem       loss  Instances       Size
      27/50     0.621G     0.3417         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 37.3it/s 0.1s
                   all      0.725      0.996

      Epoch    GPU_mem       loss  Instances       Size
      28/50     0.621G     0.2677         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 34.2it/s 0.1s
                   all      0.771      0.989

      Epoch    GPU_mem       loss  Instances       Size
      29/50     0.621G     0.2398         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.7it/s 0.2s
                   all      0.715      0.986

      Epoch    GPU_mem       loss  Instances       Size
      30/50     0.621G     0.2859         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 46.1it/s 0.1s
                   all      0.754      0.989

      Epoch    GPU_mem       loss  Instances       Size
      31/50     0.621G     0.2553         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 21.8it/s 0.2s
                   all      0.761      0.989

      Epoch    GPU_mem       loss  Instances       Size
      32/50     0.621G     0.2459         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 33.9it/s 0.1s
                   all      0.768      0.993

      Epoch    GPU_mem       loss  Instances       Size
      33/50     0.621G     0.2102         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 25.3it/s 0.2s
                   all      0.775      0.993

      Epoch    GPU_mem       loss  Instances       Size
      34/50     0.621G     0.2513         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 32.5it/s 0.2s
                   all      0.761      0.996

      Epoch    GPU_mem       loss  Instances       Size
      35/50     0.621G     0.1944         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 37.4it/s 0.1s
                   all      0.757      0.989

      Epoch    GPU_mem       loss  Instances       Size
      36/50     0.621G     0.2257         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 28.4it/s 0.2s
                   all      0.768      0.993

      Epoch    GPU_mem       loss  Instances       Size
      37/50     0.621G     0.2099         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 32.5it/s 0.2s
                   all      0.775      0.993

      Epoch    GPU_mem       loss  Instances       Size
      38/50     0.621G      0.214         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 35.0it/s 0.1s
                   all      0.785      0.989

      Epoch    GPU_mem       loss  Instances       Size
      39/50     0.621G     0.1913         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 18.9it/s 0.3s
                   all      0.771      0.989

      Epoch    GPU_mem       loss  Instances       Size
      40/50     0.621G     0.1608         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 40.9it/s 0.1s
                   all      0.768      0.996

      Epoch    GPU_mem       loss  Instances       Size
      41/50     0.621G     0.1592         27        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 20.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 18.7it/s 0.3s
                   all      0.771      0.993

      Epoch    GPU_mem       loss  Instances       Size
      42/50     0.621G     0.1588         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 20.5it/s 0.2s
                   all      0.757      0.993

      Epoch    GPU_mem       loss  Instances       Size
      43/50     0.621G     0.1679         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 30.7it/s 0.2s
                   all      0.775      0.993

      Epoch    GPU_mem       loss  Instances       Size
      44/50     0.621G      0.135         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 35.2it/s 0.1s
                   all      0.775      0.993

      Epoch    GPU_mem       loss  Instances       Size
      45/50     0.621G     0.1492         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 31.9it/s 0.2s
                   all      0.778      0.993

      Epoch    GPU_mem       loss  Instances       Size
      46/50     0.621G     0.1582         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 14.9it/s 0.3s
                   all      0.782      0.993

      Epoch    GPU_mem       loss  Instances       Size
      47/50     0.621G     0.1195         27        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 25.0it/s 0.2s
                   all      0.778      0.993

      Epoch    GPU_mem       loss  Instances       Size
      48/50     0.621G     0.1701         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 29.8it/s 0.2s
                   all      0.771      0.993

      Epoch    GPU_mem       loss  Instances       Size
      49/50     0.621G     0.1554         27        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 28.6it/s 0.2s
                   all      0.771      0.993

      Epoch    GPU_mem       loss  Instances       Size
      50/50     0.621G     0.1104         27        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 32.5it/s 0.2s
                   all      0.778      0.993

50 epochs completed in 0.238 hours.
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5/weights/last.pt, 3.2MB
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5/weights/best.pt, 3.2MB

Validating /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5/weights/best.pt...
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
YOLO11n-cls summary (fused): 47 layers, 1,534,991 parameters, 0 gradients, 3.2 GFLOPs
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 988 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 284 images in 7 classes ✅
test: /content/drive/MyDrive/MMOTU_splits_full/test... found 144 images in 7 classes ✅
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5s
                   all      0.782      0.993
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5

ultralytics.utils.metrics.ClassifyMetrics object with attributes:

confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f13ac4b40e0>
curves: []
curves_results: []
fitness: 0.8873239457607269
keys: ['metrics/accuracy_top1', 'metrics/accuracy_top5']
results_dict: {'metrics/accuracy_top1': 0.7816901206970215, 'metrics/accuracy_top5': 0.9929577708244324, 'fitness': 0.8873239457607269}
save_dir: PosixPath('/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5')
speed: {'preprocess': 0.10240752112942676, 'inference': 0.4678354471860997, 'loss': 0.0016220739434828202, 'postprocess': 0.0003224154906874132}
task: 'classify'
top1: 0.7816901206970215
top5: 0.9929577708244324

**Reasoning**:
The YOLOv11 training was successfully completed. Now, I will re-verify the image counts in each split to confirm the data integrity after the complete copying process and before proceeding to evaluate the YOLOv11 model and train the YOLOv12 model.

In [ ]:
import os
from collections import defaultdict

split_counts = defaultdict(lambda: defaultdict(int))

print("Verifying image counts...")

for split in splits:
    for cls_name in CLASS_MAP.values():
        cls_path = os.path.join(OUTPUT_ROOT, split, cls_name)
        if os.path.exists(cls_path):
            # Count only image files (e.g., .jpg, .png)
            image_files = [f for f in os.listdir(cls_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
            count = len(image_files)
            split_counts[split][cls_name] = count

print("\nImage counts per split and class:")
for split, classes in split_counts.items():
    print(f"  {split.capitalize()} set:")
    for cls_name, count in classes.items():
        print(f"    {cls_name}: {count} images")

total_images_per_class = defaultdict(int)
overall_total_images = 0

print("\nTotal images per class across all splits:")
for split, classes in split_counts.items():
    for cls_name, count in classes.items():
        total_images_per_class[cls_name] += count
        overall_total_images += count

for cls_name, total_count in total_images_per_class.items():
    print(f"  {cls_name}: {total_count} images")

print(f"\nOverall total images: {overall_total_images}")

# Expected total (excluding class 7: 1598 - 182 = 1416)
# This value should be consistent with the original count of all_data (1416) if the split ratios were applied perfectly.
# Let's verify against all_data length first.
expected_total_from_all_data = len(all_data)
print(f"Expected total images from original filtered data (all_data): {expected_total_from_all_data}")

if overall_total_images == expected_total_from_all_data:
    print("\nVerification successful: Total images match expected count!")
else:
    print(f"\nVerification failed: Total images ({overall_total_images}) do not match expected count ({expected_total_from_all_data}).")

Verifying image counts...

Image counts per split and class:
  Train set:
    Normal_Ovary: 235 images
    Simple_Cyst: 153 images
    Teratoma: 235 images
    Serous_Cystadenoma: 61 images
    Mucinous_Cystadenoma: 46 images
    Chocolate_Cyst: 186 images
    Theca_Cell_Tumor: 72 images
  Val set:
    Normal_Ovary: 67 images
    Simple_Cyst: 44 images
    Teratoma: 67 images
    Serous_Cystadenoma: 18 images
    Mucinous_Cystadenoma: 13 images
    Chocolate_Cyst: 54 images
    Theca_Cell_Tumor: 21 images
  Test set:
    Normal_Ovary: 34 images
    Simple_Cyst: 22 images
    Teratoma: 34 images
    Serous_Cystadenoma: 9 images
    Mucinous_Cystadenoma: 7 images
    Chocolate_Cyst: 27 images
    Theca_Cell_Tumor: 11 images

Total images per class across all splits:
  Normal_Ovary: 336 images
  Simple_Cyst: 219 images
  Teratoma: 336 images
  Serous_Cystadenoma: 88 images
  Mucinous_Cystadenoma: 66 images
  Chocolate_Cyst: 267 images
  Theca_Cell_Tumor: 104 images

Overall total images: 1416
Expected total images from original filtered data (all_data): 1416

Verification successful: Total images match expected count!

## Evaluate YOLOv11 Model Performance

### Subtask:
Load the best weights from the trained YOLOv11 model, perform predictions on the test set, and generate a classification report.

## Summary:

### Data Analysis Key Findings
*   The training of the YOLOv11 classification model, which was previously interrupted, has been restarted.
*   The model is configured to train for 50 epochs using a batch size of 32 and an input image size of 224x224 pixels.
*   Various data augmentation techniques are applied during training, including horizontal flipping (50\% probability), vertical flipping (30\% probability), rotation (up to 10 degrees), translation (up to 10\%), scaling (up to 50\%), and adjustments to HSV color space (hue by 0.015, saturation by 0.7, value by 0.4).

### Insights or Next Steps
*   Monitor the training progress and validation metrics (e.g., accuracy, loss) during the 50 epochs to ensure the model converges effectively and to identify any potential issues like overfitting or underfitting.
*   Upon completion of the training, evaluate the final model performance on a separate test dataset using appropriate classification metrics such as precision, recall, F1-score, and accuracy to determine its readiness for deployment.

# Task
The YOLOv11 classification model training was successfully completed. Now, I will evaluate its performance on the test set.

## Evaluate YOLOv11 Model Performance

### Subtask:
Load the best weights from the newly trained YOLOv11 model, perform predictions on the test set, and generate a classification report.

### Reasoning:
To evaluate the performance of the recently trained YOLOv11 model, I need to load the `best.pt` weights from the `yolov11_cls` directory within `"/content/drive/MyDrive/YOLO_MMOTU_RESULTS"`. Then, I will gather all image paths from the `test` split of the dataset, perform predictions using the loaded model, and finally generate a classification report to assess its accuracy, precision, recall, and F1-score across all classes.

```python
from ultralytics import YOLO
from sklearn.metrics import classification_report
import os

# Define the path to the best weights of the newly trained YOLOv11 model
yolov11_weights_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls/weights/best.pt"

# Load the YOLOv11 model with the best weights
model_v11_eval = YOLO(yolov11_weights_path)

# Prepare test image paths (ensure it's updated after data split re-execution)
test_image_paths_v11 = []
test_root = os.path.join(OUTPUT_ROOT, "test")

for cls_name in CLASS_MAP.values():
    cls_path = os.path.join(test_root, cls_name)
    if os.path.exists(cls_path):
        for img_file in os.listdir(cls_path):
            if img_file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.webp')):
                test_image_paths_v11.append(os.path.join(cls_path, img_file))

# Perform prediction on the collected list of test image paths
print(f"Performing predictions on {len(test_image_paths_v11)} test images for YOLOv11...")
results_v11 = model_v11_eval.predict(
    source=test_image_paths_v11,
    imgsz=IMGSZ,
    conf=0.25, # Default confidence threshold for classification
    verbose=False # Suppress verbose output for each image
)

y_true_v11 = []
y_pred_v11 = []

# Assuming CLASS_MAP is available from previous cells.
class_names_list = list(CLASS_MAP.values())
class_to_idx = {name: i for i, name in enumerate(class_names_list)}

for i, r in enumerate(results_v11):
    # Get the top1 predicted class index
    predicted_idx = r.probs.top1
    y_pred_v11.append(predicted_idx)

    # Extract the true class label from the image path
    true_class_name = os.path.basename(os.path.dirname(r.path))
    y_true_v11.append(class_to_idx[true_class_name])

# Generate and print the classification report
print("\nClassification Report for YOLOv11:")
report_v11 = classification_report(y_true_v11, y_pred_v11, target_names=class_names_list)
print(report_v11)

# Store the accuracy for comparison later
yolov11_accuracy = model_v11_eval.metrics.top1 if hasattr(model_v11_eval, 'metrics') else None
if yolov11_accuracy:
    print(f"\nYOLOv11 Test Top-1 Accuracy from training metrics: {yolov11_accuracy:.4f}")
```

## Prepare YOLOv12 Configuration

### Subtask:
Verify that the Ultralytics repository is cloned and the custom YOLOv12 YAML configuration file with nc: 7 is correctly created and located.

**Reasoning**:
To verify that the Ultralytics repository is cloned, I will check for the existence of the 'ultralytics' directory in the current working directory.

In [ ]:
import os

# Verify 'ultralytics' directory exists
ultralytics_dir = 'ultralytics'
if os.path.isdir(ultralytics_dir):
    print(f"Directory '{ultralytics_dir}' found. Ultralytics repository is likely cloned.")
else:
    print(f"Directory '{ultralytics_dir}' not found. Please ensure the repository is cloned.")

Directory 'ultralytics' found. Ultralytics repository is likely cloned.

**Reasoning**:
To confirm the existence and content of the custom YOLOv12 YAML configuration file, I will check for its presence and then read its content to ensure 'nc: 7' is correctly set.

In [ ]:
import os

yaml_file_path = "/content/yolo12-cls-mmoutu.yaml"

# Confirm the existence of the custom YAML configuration file
if os.path.exists(yaml_file_path):
    print(f"Custom YAML configuration file '{yaml_file_path}' found.")

    # Optionally, inspect the content to ensure 'nc: 7' is correctly set
    try:
        with open(yaml_file_path, "r") as f:
            content = f.read()
            print("Content of yolo12-cls-mmoutu.yaml:")
            print(content)
            if "nc: 7" in content:
                print("Verification successful: 'nc: 7' is correctly set in the YAML file.")
            else:
                print("Verification warning: 'nc: 7' not found or incorrect in the YAML file.")
    except Exception as e:
        print(f"Error reading YAML file: {e}")
else:
    print(f"Custom YAML configuration file '{yaml_file_path}' not found.")

Custom YAML configuration file '/content/yolo12-cls-mmoutu.yaml' found.
Content of yolo12-cls-mmoutu.yaml:

# YOLO12-cls image classification model

nc: 7

scales:
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024]
  m: [0.50, 1.00, 512]
  l: [1.00, 1.50, 512]
  x: [1.00, 1.50, 512]

backbone:
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [-1, 4, A2C2f, [512, True, 4]]
  - [-1, 1, Conv, [1024, 3, 2]]
  - [-1, 4, A2C2f, [1024, True, 1]]

head:
  - [-1, 1, Classify, [nc]]

Verification successful: 'nc: 7' is correctly set in the YAML file.

## Evaluate YOLOv11 Model Performance

### Subtask:
Load the best weights from the newly trained YOLOv11 model, perform predictions on the test set, and generate a classification report.

**Reasoning**:
To evaluate the performance of the newly trained YOLOv11 model, I will execute the code block that loads its best weights, performs predictions on the test set, and generates a classification report.

In [ ]:
from ultralytics import YOLO
from sklearn.metrics import classification_report
import os

# Define the path to the best weights of the newly trained YOLOv11 model
yolov11_weights_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls/weights/best.pt"

# Load the YOLOv11 model with the best weights
model_v11_eval = YOLO(yolov11_weights_path)

# Prepare test image paths (ensure it's updated after data split re-execution)
test_image_paths_v11 = []
test_root = os.path.join(OUTPUT_ROOT, "test")

for cls_name in CLASS_MAP.values():
    cls_path = os.path.join(test_root, cls_name)
    if os.path.exists(cls_path):
        for img_file in os.listdir(cls_path):
            if img_file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.webp')):
                test_image_paths_v11.append(os.path.join(cls_path, img_file))

# Perform prediction on the collected list of test image paths
print(f"Performing predictions on {len(test_image_paths_v11)} test images for YOLOv11...")
results_v11 = model_v11_eval.predict(
    source=test_image_paths_v11,
    imgsz=IMGSZ,
    conf=0.25, # Default confidence threshold for classification
    verbose=False # Suppress verbose output for each image
)

y_true_v11 = []
y_pred_v11 = []

# Assuming CLASS_MAP is available from previous cells.
class_names_list = list(CLASS_MAP.values())
class_to_idx = {name: i for i, name in enumerate(class_names_list)}

for i, r in enumerate(results_v11):
    # Get the top1 predicted class index
    predicted_idx = r.probs.top1
    y_pred_v11.append(predicted_idx)

    # Extract the true class label from the image path
    # The path structure is /content/MMOTU_splits_full/test/CLASS_NAME/image.jpg
    true_class_name = os.path.basename(os.path.dirname(r.path))
    y_true_v11.append(class_to_idx[true_class_name])

# Generate and print the classification report
print("\nClassification Report for YOLOv11:")
report_v11 = classification_report(y_true_v11, y_pred_v11, target_names=class_names_list)
print(report_v11)

# Store the accuracy for comparison later
yolov11_accuracy = model_v11_eval.metrics.top1 if hasattr(model_v11_eval, 'metrics') else None
if yolov11_accuracy:
    print(f"\nYOLOv11 Test Top-1 Accuracy from training metrics: {yolov11_accuracy:.4f}")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls/weights/best.pt'

**Reasoning**:
The previous attempt to evaluate the YOLOv11 model failed because the path to its `best.pt` weights file was incorrect. Based on the latest successful training run (`fa2a8e63`), the model weights were saved to `/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5/weights/best.pt`. I will update the `yolov11_weights_path` variable to this correct location and re-execute the evaluation code.

In [ ]:
from ultralytics import YOLO
from sklearn.metrics import classification_report
import os

# Define the path to the best weights of the newly trained YOLOv11 model
yolov11_weights_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5/weights/best.pt"

# Load the YOLOv11 model with the best weights
model_v11_eval = YOLO(yolov11_weights_path)

# Prepare test image paths (ensure it's updated after data split re-execution)
test_image_paths_v11 = []
test_root = os.path.join(OUTPUT_ROOT, "test")

for cls_name in CLASS_MAP.values():
    cls_path = os.path.join(test_root, cls_name)
    if os.path.exists(cls_path):
        for img_file in os.listdir(cls_path):
            if img_file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.webp')):
                test_image_paths_v11.append(os.path.join(cls_path, img_file))

# Perform prediction on the collected list of test image paths
print(f"Performing predictions on {len(test_image_paths_v11)} test images for YOLOv11...")
results_v11 = model_v11_eval.predict(
    source=test_image_paths_v11,
    imgsz=IMGSZ,
    conf=0.25, # Default confidence threshold for classification
    verbose=False # Suppress verbose output for each image
)

y_true_v11 = []
y_pred_v11 = []

# Assuming CLASS_MAP is available from previous cells.
class_names_list = list(CLASS_MAP.values())
class_to_idx = {name: i for i, name in enumerate(class_names_list)}

for i, r in enumerate(results_v11):
    # Get the top1 predicted class index
    predicted_idx = r.probs.top1
    y_pred_v11.append(predicted_idx)

    # Extract the true class label from the image path
    # The path structure is /content/MMOTU_splits_full/test/CLASS_NAME/image.jpg
    true_class_name = os.path.basename(os.path.dirname(r.path))
    y_true_v11.append(class_to_idx[true_class_name])

# Generate and print the classification report
print("\nClassification Report for YOLOv11:")
report_v11 = classification_report(y_true_v11, y_pred_v11, target_names=class_names_list)
print(report_v11)

# Store the accuracy for comparison later
yolov11_accuracy = model_v11_eval.metrics.top1 if hasattr(model_v11_eval, 'metrics') else None
if yolov11_accuracy:
    print(f"\nYOLOv11 Test Top-1 Accuracy from training metrics: {yolov11_accuracy:.4f}")

Performing predictions on 144 test images for YOLOv11...

Classification Report for YOLOv11:
                      precision    recall  f1-score   support

        Normal_Ovary       0.06      0.06      0.06        34
         Simple_Cyst       0.00      0.00      0.00        22
            Teratoma       0.06      0.06      0.06        34
  Serous_Cystadenoma       0.58      0.78      0.67         9
Mucinous_Cystadenoma       0.00      0.00      0.00         7
      Chocolate_Cyst       0.00      0.00      0.00        27
    Theca_Cell_Tumor       0.82      0.82      0.82        11

            accuracy                           0.14       144
           macro avg       0.22      0.24      0.23       144
        weighted avg       0.13      0.14      0.13       144

AttributeError: 'NoneType' object has no attribute 'top1'

**Reasoning**:
The previous code failed because `model_v11_eval.metrics` is not populated after calling `predict()`. To get the overall accuracy, I will extract it from the generated `classification_report` instead of trying to access a non-existent attribute.

In [ ]:
from ultralytics import YOLO
from sklearn.metrics import classification_report
import os

# Define the path to the best weights of the newly trained YOLOv11 model
yolov11_weights_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls5/weights/best.pt"

# Load the YOLOv11 model with the best weights
model_v11_eval = YOLO(yolov11_weights_path)

# Prepare test image paths (ensure it's updated after data split re-execution)
test_image_paths_v11 = []
test_root = os.path.join(OUTPUT_ROOT, "test")

for cls_name in CLASS_MAP.values():
    cls_path = os.path.join(test_root, cls_name)
    if os.path.exists(cls_path):
        for img_file in os.listdir(cls_path):
            if img_file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.webp')):
                test_image_paths_v11.append(os.path.join(cls_path, img_file))

# Perform prediction on the collected list of test image paths
print(f"Performing predictions on {len(test_image_paths_v11)} test images for YOLOv11...")
results_v11 = model_v11_eval.predict(
    source=test_image_paths_v11,
    imgsz=IMGSZ,
    conf=0.25, # Default confidence threshold for classification
    verbose=False # Suppress verbose output for each image
)

y_true_v11 = []
y_pred_v11 = []

# Assuming CLASS_MAP is available from previous cells.
class_names_list = list(CLASS_MAP.values())
class_to_idx = {name: i for i, name in enumerate(class_names_list)}

for i, r in enumerate(results_v11):
    # Get the top1 predicted class index
    predicted_idx = r.probs.top1
    y_pred_v11.append(predicted_idx)

    # Extract the true class label from the image path
    # The path structure is /content/MMOTU_splits_full/test/CLASS_NAME/image.jpg
    true_class_name = os.path.basename(os.path.dirname(r.path))
    y_true_v11.append(class_to_idx[true_class_name])

# Generate and print the classification report
print("\nClassification Report for YOLOv11:")
report_v11 = classification_report(y_true_v11, y_pred_v11, target_names=class_names_list)
print(report_v11)

# Extract accuracy from the classification report
# The classification_report returns a string, so we need to parse it or use accuracy_score
from sklearn.metrics import accuracy_score
yolov11_accuracy = accuracy_score(y_true_v11, y_pred_v11)

print(f"\nYOLOv11 Test Top-1 Accuracy: {yolov11_accuracy:.4f}")

Performing predictions on 144 test images for YOLOv11...

Classification Report for YOLOv11:
                      precision    recall  f1-score   support

        Normal_Ovary       0.06      0.06      0.06        34
         Simple_Cyst       0.00      0.00      0.00        22
            Teratoma       0.06      0.06      0.06        34
  Serous_Cystadenoma       0.58      0.78      0.67         9
Mucinous_Cystadenoma       0.00      0.00      0.00         7
      Chocolate_Cyst       0.00      0.00      0.00        27
    Theca_Cell_Tumor       0.82      0.82      0.82        11

            accuracy                           0.14       144
           macro avg       0.22      0.24      0.23       144
        weighted avg       0.13      0.14      0.13       144


YOLOv11 Test Top-1 Accuracy: 0.1389

## Evaluate YOLOv12 Model Performance

### Subtask:
Load the best weights from the trained YOLOv12 model, perform predictions on the test set, and generate a classification report.

**Reasoning**:
To evaluate the performance of the trained YOLOv12 model, I will load its best weights, prepare the test image paths, perform predictions, extract true and predicted labels, and then generate a comprehensive classification report including overall accuracy.

In [ ]:
from ultralytics import YOLO
from sklearn.metrics import classification_report, accuracy_score
import os

# Define the path to the best weights of the trained YOLOv12 model
yolov12_weights_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/best.pt"

# Load the YOLOv12 model with the best weights
model_v12_eval = YOLO(yolov12_weights_path)

# Prepare test image paths (ensure it's updated after data split re-execution)
test_image_paths_v12 = []
test_root = os.path.join(OUTPUT_ROOT, "test")

for cls_name in CLASS_MAP.values():
    cls_path = os.path.join(test_root, cls_name)
    if os.path.exists(cls_path):
        for img_file in os.listdir(cls_path):
            if img_file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.webp')):
                test_image_paths_v12.append(os.path.join(cls_path, img_file))

# Perform prediction on the collected list of test image paths
print(f"Performing predictions on {len(test_image_paths_v12)} test images for YOLOv12...")
results_v12 = model_v12_eval.predict(
    source=test_image_paths_v12,
    imgsz=IMGSZ,
    conf=0.25, # Default confidence threshold for classification
    verbose=False # Suppress verbose output for each image
)

y_true_v12 = []
y_pred_v12 = []

# Assuming CLASS_MAP is available from previous cells.
# class_names_list and class_to_idx are already defined in kernel state

for i, r in enumerate(results_v12):
    # Get the top1 predicted class index
    predicted_idx = r.probs.top1
    y_pred_v12.append(predicted_idx)

    # Extract the true class label from the image path
    # The path structure is /content/MMOTU_splits_full/test/CLASS_NAME/image.jpg
    true_class_name = os.path.basename(os.path.dirname(r.path))
    y_true_v12.append(class_to_idx[true_class_name])

# Generate and print the classification report
print("\nClassification Report for YOLOv12:")
report_v12 = classification_report(y_true_v12, y_pred_v12, target_names=class_names_list)
print(report_v12)

# Calculate and print the overall Top-1 accuracy
yolov12_accuracy = accuracy_score(y_true_v12, y_pred_v12)
print(f"\nYOLOv12 Test Top-1 Accuracy: {yolov12_accuracy:.4f}")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/best.pt'

# Task
To address the `FileNotFoundError` encountered when trying to evaluate the YOLOv12 model, I will first verify the contents of the directory where the weights are expected to be saved. This will help confirm if the `best.pt` file exists and if the path is correct.

**Action:** List the contents of the `/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/` directory.

```python
!ls -l /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/
```

## List contents of YOLOv12 weights directory

### Subtask:
Verify the contents of the directory where the YOLOv12 model weights are expected to be saved to confirm if the `best.pt` file exists and if the path is correct.

**Reasoning**:
To verify if the `best.pt` file exists in the YOLOv12 weights directory, I will execute the specified shell command to list its contents.

In [ ]:
model_v12_results_dir = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/"
!ls -l {model_v12_results_dir}

ls: cannot access '/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/': No such file or directory

# Task
The previous attempt to locate the YOLOv12 weights failed because the directory `/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/` was not found. This indicates a potential mismatch between the expected and actual output directory of the YOLOv12 training.

Reviewing the output of the YOLOv12 training run (cell `fMAvVuPps4_8`), the results were saved to `[1m/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls[0m`. Therefore, the path to the best weights should be `/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/best.pt`.

I will now verify this path and then proceed with the evaluation.

```python
import os

# Define the correct path to the best weights of the trained YOLOv12 model
yolov12_weights_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/best.pt"

# Verify the existence of the directory and the file
if os.path.exists(yolov12_weights_path):
    print(f"YOLOv12 best weights found at: {yolov12_weights_path}")
else:
    print(f"Error: YOLOv12 best weights not found at: {yolov12_weights_path}")
    print("Listing contents of the parent directory:")
    !ls -l "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/"
```

## Verify YOLOv12 weights path and evaluate model performance (retry)

### Subtask:
Identify the actual directory of the trained YOLOv12 model weights, then load the best weights, perform predictions on the test set, and generate a classification report.

**Reasoning**:
The previous attempt to list the contents of the YOLOv12 weights directory failed because the `yolov12_cls` directory itself might not exist, or the path was incorrect. To identify the actual directory where the YOLOv12 training results are stored, I need to list the parent directory, `/content/drive/MyDrive/YOLO_MMOTU_RESULTS/`.

In [ ]:
import os

results_base_dir = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/"
print(f"Listing contents of: {results_base_dir}")
!ls -l {results_base_dir}

Listing contents of: /content/drive/MyDrive/YOLO_MMOTU_RESULTS/
total 12
drwx------ 3 root root 4096 Dec 21 11:53 yolov11_cls5
drwx------ 3 root root 4096 Dec 21 11:15 yolov12_cls2
drwx------ 2 root root 4096 Dec 19 09:15 yolov8_cls_full2

**Reasoning**:
Based on the output from the previous cell, the correct directory for the YOLOv12 model results is `yolov12_cls2`. I will now update the `yolov12_weights_path` and proceed with loading the model, performing predictions on the test set, and generating the classification report as instructed.

In [ ]:
from ultralytics import YOLO
from sklearn.metrics import classification_report, accuracy_score
import os

# Define the path to the best weights of the trained YOLOv12 model using the identified directory
yolov12_weights_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls2/weights/best.pt"

# Load the YOLOv12 model with the best weights
model_v12_eval = YOLO(yolov12_weights_path)

# Prepare test image paths (ensure it's updated after data split re-execution)
test_image_paths_v12 = []
test_root = os.path.join(OUTPUT_ROOT, "test")

for cls_name in CLASS_MAP.values():
    cls_path = os.path.join(test_root, cls_name)
    if os.path.exists(cls_path):
        for img_file in os.listdir(cls_path):
            if img_file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.webp')):
                test_image_paths_v12.append(os.path.join(cls_path, img_file))

# Perform prediction on the collected list of test image paths
print(f"Performing predictions on {len(test_image_paths_v12)} test images for YOLOv12...")
results_v12 = model_v12_eval.predict(
    source=test_image_paths_v12,
    imgsz=IMGSZ,
    conf=0.25, # Default confidence threshold for classification
    verbose=False # Suppress verbose output for each image
)

y_true_v12 = []
y_pred_v12 = []

# Assuming CLASS_MAP is available from previous cells.
# class_names_list and class_to_idx are already defined in kernel state

for i, r in enumerate(results_v12):
    # Get the top1 predicted class index
    predicted_idx = r.probs.top1
    y_pred_v12.append(predicted_idx)

    # Extract the true class label from the image path
    # The path structure is /content/MMOTU_splits_full/test/CLASS_NAME/image.jpg
    true_class_name = os.path.basename(os.path.dirname(r.path))
    y_true_v12.append(class_to_idx[true_class_name])

# Generate and print the classification report
print("\nClassification Report for YOLOv12:")
report_v12 = classification_report(y_true_v12, y_pred_v12, target_names=class_names_list)
print(report_v12)

# Calculate and print the overall Top-1 accuracy
yolov12_accuracy = accuracy_score(y_true_v12, y_pred_v12)
print(f"\nYOLOv12 Test Top-1 Accuracy: {yolov12_accuracy:.4f}")

Performing predictions on 144 test images for YOLOv12...

Classification Report for YOLOv12:
                      precision    recall  f1-score   support

        Normal_Ovary       0.05      0.06      0.05        34
         Simple_Cyst       0.00      0.00      0.00        22
            Teratoma       0.10      0.12      0.11        34
  Serous_Cystadenoma       0.00      0.00      0.00         9
Mucinous_Cystadenoma       0.07      0.29      0.11         7
      Chocolate_Cyst       0.15      0.19      0.17        27
    Theca_Cell_Tumor       1.00      0.18      0.31        11

            accuracy                           0.10       144
           macro avg       0.20      0.12      0.11       144
        weighted avg       0.14      0.10      0.10       144


YOLOv12 Test Top-1 Accuracy: 0.1042

In [ ]:
from ultralytics import YOLO

# Use the dataset directory (ImageFolder format) for classification
DATA_DIR = "/content/drive/MyDrive/NNDL/MMOTU/OTU_2d/dataset_cls"

model = YOLO("yolov8n-cls.pt")   # tiny classifier

model.train(
    data=DATA_DIR,       # <--- IMPORTANT: pass the folder, not the yaml
    epochs=20,
    batch=2,             # CPU small batch
    imgsz=224,
    lr0=1e-3,
    optimizer="AdamW",
    weight_decay=1e-4,
    project="/content/drive/MyDrive/NNDL/MMOTU/YOLO_Cls_Results",
    name="yolov8n_cls_cpu_correct",
    device="cpu",        # CPU training (you said you'll use CPU)
    workers=0
)