In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!unzip /content/drive/MyDrive/MMOTU.zip -d /content/drive/MyDrive/MMOTU

unzip:  cannot find or open /content/drive/MyDrive/MMOTU.zip, /content/drive/MyDrive/MMOTU.zip.zip or /content/drive/MyDrive/MMOTU.zip.ZIP.

In [ ]:
!ls /content/drive/MyDrive/MMOTU

ls: cannot access '/content/drive/MyDrive/MMOTU': No such file or directory

In [ ]:
import os, shutil

BASE_PATH = "/content/drive/MyDrive/MMOTU/MMOTU/OTU_2d"
IMG_PATH = os.path.join(BASE_PATH, "images")
ANN_PATH = os.path.join(BASE_PATH, "annotations")

OUT_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

splits = ["train", "val", "test"]

In [ ]:
import os
import shutil
from collections import defaultdict, Counter
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [ ]:
# Original dataset paths
BASE_DATASET = "/content/drive/MyDrive/MMOTU/MMOTU/OTU_2d"
IMAGE_DIR = os.path.join(BASE_DATASET, "images")
TRAIN_CLS = os.path.join(BASE_DATASET, "train_cls.txt")
VAL_CLS = os.path.join(BASE_DATASET, "val_cls.txt")

# Final dataset path
OUTPUT_ROOT = "/content/MMOTU_splits_full"

In [ ]:
# Original class IDs → Clinical labels
CLASS_MAP = {
    0: "Normal_Ovary",
    1: "Simple_Cyst",
    2: "Teratoma",
    3: "Serous_Cystadenoma",
    4: "Mucinous_Cystadenoma",
    5: "Chocolate_Cyst",
    6: "Theca_Cell_Tumor"
    # class 7 (High Grade Serous) is intentionally removed
}

In [ ]:
def read_labels(label_file):
    data = []
    with open(label_file, "r") as f:
        for line in f:
            img, cls = line.strip().split()
            cls = int(cls)
            if cls in CLASS_MAP:  # removes class 7 automatically
                data.append((img, cls))
    return data

train_data = read_labels(TRAIN_CLS)
val_data = read_labels(VAL_CLS)

all_data = train_data + val_data

In [ ]:
class_counts = Counter([cls for _, cls in all_data])
print("Class distribution after removal:")
for cls, count in class_counts.items():
    print(CLASS_MAP[cls], ":", count)

Class distribution after removal:
Chocolate_Cyst : 267
Serous_Cystadenoma : 88
Simple_Cyst : 219
Theca_Cell_Tumor : 104
Teratoma : 336
Normal_Ovary : 336
Mucinous_Cystadenoma : 66

In [ ]:
class_images = defaultdict(list)

for img_name, cls in all_data:
    img_path = os.path.join(IMAGE_DIR, img_name)
    if os.path.exists(img_path):
        class_images[CLASS_MAP[cls]].append(img_path)

In [ ]:
for split in ["train", "val", "test"]:
    for cls_name in CLASS_MAP.values():
        os.makedirs(os.path.join(OUTPUT_ROOT, split, cls_name), exist_ok=True)

In [ ]:
train_ratio = 0.7
val_ratio = 0.2
test_ratio = 0.1

In [23]:
for cls_name in CLASS_MAP.values():
    images = class_images[cls_name]

    # Split data into train, val, test
    train_imgs, temp_imgs = train_test_split(images, train_size=train_ratio, random_state=42)
    val_imgs, test_imgs = train_test_split(temp_imgs, test_size=test_ratio/(val_ratio + test_ratio), random_state=42)

    # Copy images to respective directories
    for img_path in tqdm(train_imgs, desc=f"Copying {cls_name} train images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "train", cls_name, os.path.basename(img_path)))
    for img_path in tqdm(val_imgs, desc=f"Copying {cls_name} val images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "val", cls_name, os.path.basename(img_path)))
    for img_path in tqdm(test_imgs, desc=f"Copying {cls_name} test images"):
        shutil.copy(img_path, os.path.join(OUTPUT_ROOT, "test", cls_name, os.path.basename(img_path)))

Copying Normal_Ovary train images: 100%|██████████| 235/235 [01:28<00:00,  2.66it/s]
Copying Normal_Ovary val images: 100%|██████████| 67/67 [00:25<00:00,  2.68it/s]
Copying Normal_Ovary test images: 100%|██████████| 34/34 [00:12<00:00,  2.80it/s]
Copying Simple_Cyst train images: 100%|██████████| 153/153 [00:57<00:00,  2.67it/s]
Copying Simple_Cyst val images: 100%|██████████| 44/44 [00:16<00:00,  2.71it/s]
Copying Simple_Cyst test images: 100%|██████████| 22/22 [00:08<00:00,  2.73it/s]
Copying Teratoma train images: 100%|██████████| 235/235 [01:26<00:00,  2.70it/s]
Copying Teratoma val images: 100%|██████████| 67/67 [00:25<00:00,  2.66it/s]
Copying Teratoma test images: 100%|██████████| 34/34 [00:13<00:00,  2.57it/s]
Copying Serous_Cystadenoma train images: 100%|██████████| 61/61 [00:21<00:00,  2.88it/s]
Copying Serous_Cystadenoma val images: 100%|██████████| 18/18 [00:06<00:00,  2.91it/s]
Copying Serous_Cystadenoma test images: 100%|██████████| 9/9 [00:03<00:00,  2.83it/s]
Copying Mucinous_Cystadenoma train images: 100%|██████████| 46/46 [00:16<00:00,  2.74it/s]
Copying Mucinous_Cystadenoma val images: 100%|██████████| 13/13 [00:04<00:00,  2.70it/s]
Copying Mucinous_Cystadenoma test images: 100%|██████████| 7/7 [00:02<00:00,  3.22it/s]
Copying Chocolate_Cyst train images: 100%|██████████| 186/186 [00:00<00:00, 303.73it/s]
Copying Chocolate_Cyst val images: 100%|██████████| 54/54 [00:08<00:00,  6.40it/s]
Copying Chocolate_Cyst test images: 100%|██████████| 27/27 [00:10<00:00,  2.66it/s]
Copying Theca_Cell_Tumor train images: 100%|██████████| 72/72 [00:25<00:00,  2.78it/s]
Copying Theca_Cell_Tumor val images: 100%|██████████| 21/21 [00:07<00:00,  2.77it/s]
Copying Theca_Cell_Tumor test images: 100%|██████████| 11/11 [00:04<00:00,  2.63it/s]

In [24]:
print("Preprocessing completed successfully!")
print("Final dataset ready for YOLO classification training.")

Preprocessing completed successfully!
Final dataset ready for YOLO classification training.

In [25]:
YOLO_AUGMENTATIONS = {
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.4,
    "degrees": 10,
    "translate": 0.1,
    "scale": 0.5,
    "fliplr": 0.5,
    "flipud": 0.0,
    "erasing": 0.4,
    "auto_augment": "randaugment"
}

In [26]:
!pip install -U ultralytics

Requirement already satisfied: ultralytics in /usr/local/lib/python3.12/dist-packages (8.3.240)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.12.0.88)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.24.0+cu126)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.31.0)
Requirement already satisfied: ultralytics-thop>=2.0.18 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.18)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2025.11.12)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)

In [28]:
import os
from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls/weights/best.pt")

test_image_paths = []
test_root = os.path.join(OUTPUT_ROOT, "test") # Use OUTPUT_ROOT for consistency

# Assuming CLASS_MAP is available from previous cells
# If not, it would need to be re-imported or defined here.
# For this context, it is available in the kernel state.
for cls_name in CLASS_MAP.values(): # Iterate through each class subdirectory
    cls_path = os.path.join(test_root, cls_name)
    if os.path.exists(cls_path):
        for img_file in os.listdir(cls_path):
            # Filter for common image file extensions
            if img_file.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.webp')):
                test_image_paths.append(os.path.join(cls_path, img_file))

# Perform prediction on the collected list of image paths
results = model.predict(
    source=test_image_paths,
    imgsz=224
)

0: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
1: 224x224 Normal_Ovary 0.99, Mucinous_Cystadenoma 0.01, Theca_Cell_Tumor 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
2: 224x224 Normal_Ovary 0.76, Simple_Cyst 0.12, Theca_Cell_Tumor 0.08, Mucinous_Cystadenoma 0.03, Teratoma 0.01, 0.3ms
3: 224x224 Normal_Ovary 1.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Teratoma 0.00, Simple_Cyst 0.00, 0.3ms
4: 224x224 Normal_Ovary 1.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
5: 224x224 Normal_Ovary 1.00, Simple_Cyst 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
6: 224x224 Normal_Ovary 1.00, Serous_Cystadenoma 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, 0.3ms
7: 224x224 Normal_Ovary 1.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Serous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
8: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
9: 224x224 Normal_Ovary 0.99, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
10: 224x224 Normal_Ovary 0.96, Teratoma 0.04, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, 0.3ms
11: 224x224 Normal_Ovary 1.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
12: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, 0.3ms
13: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
14: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
15: 224x224 Normal_Ovary 0.99, Theca_Cell_Tumor 0.01, Teratoma 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
16: 224x224 Normal_Ovary 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
17: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
18: 224x224 Serous_Cystadenoma 0.76, Normal_Ovary 0.21, Chocolate_Cyst 0.03, Teratoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
19: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
20: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, Simple_Cyst 0.00, 0.3ms
21: 224x224 Chocolate_Cyst 0.99, Serous_Cystadenoma 0.01, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
22: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, Teratoma 0.00, 0.3ms
23: 224x224 Normal_Ovary 0.98, Simple_Cyst 0.01, Theca_Cell_Tumor 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
24: 224x224 Normal_Ovary 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Serous_Cystadenoma 0.00, 0.3ms
25: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
26: 224x224 Normal_Ovary 1.00, Serous_Cystadenoma 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
27: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
28: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
29: 224x224 Normal_Ovary 1.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
30: 224x224 Normal_Ovary 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
31: 224x224 Normal_Ovary 1.00, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
32: 224x224 Normal_Ovary 1.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
33: 224x224 Normal_Ovary 0.99, Serous_Cystadenoma 0.01, Teratoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, 0.3ms
34: 224x224 Simple_Cyst 0.99, Teratoma 0.00, Mucinous_Cystadenoma 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
35: 224x224 Simple_Cyst 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Teratoma 0.00, 0.3ms
36: 224x224 Chocolate_Cyst 0.29, Mucinous_Cystadenoma 0.24, Normal_Ovary 0.21, Serous_Cystadenoma 0.13, Simple_Cyst 0.08, 0.3ms
37: 224x224 Simple_Cyst 0.49, Teratoma 0.45, Mucinous_Cystadenoma 0.07, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
38: 224x224 Simple_Cyst 0.99, Theca_Cell_Tumor 0.01, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
39: 224x224 Simple_Cyst 0.82, Teratoma 0.16, Theca_Cell_Tumor 0.02, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, 0.3ms
40: 224x224 Serous_Cystadenoma 0.98, Simple_Cyst 0.02, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, 0.3ms
41: 224x224 Simple_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
42: 224x224 Simple_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
43: 224x224 Simple_Cyst 1.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
44: 224x224 Mucinous_Cystadenoma 0.96, Simple_Cyst 0.04, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
45: 224x224 Simple_Cyst 0.97, Normal_Ovary 0.03, Theca_Cell_Tumor 0.00, Teratoma 0.00, Serous_Cystadenoma 0.00, 0.3ms
46: 224x224 Theca_Cell_Tumor 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
47: 224x224 Simple_Cyst 0.60, Teratoma 0.29, Mucinous_Cystadenoma 0.10, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
48: 224x224 Chocolate_Cyst 0.99, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Simple_Cyst 0.00, Teratoma 0.00, 0.3ms
49: 224x224 Simple_Cyst 1.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
50: 224x224 Simple_Cyst 0.99, Theca_Cell_Tumor 0.01, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
51: 224x224 Simple_Cyst 0.99, Teratoma 0.01, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
52: 224x224 Simple_Cyst 1.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
53: 224x224 Simple_Cyst 1.00, Normal_Ovary 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
54: 224x224 Simple_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
55: 224x224 Teratoma 0.41, Theca_Cell_Tumor 0.31, Mucinous_Cystadenoma 0.20, Simple_Cyst 0.06, Normal_Ovary 0.02, 0.3ms
56: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, 0.3ms
57: 224x224 Teratoma 0.99, Mucinous_Cystadenoma 0.01, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, 0.3ms
58: 224x224 Teratoma 1.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
59: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
60: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
61: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, 0.3ms
62: 224x224 Serous_Cystadenoma 0.81, Normal_Ovary 0.16, Theca_Cell_Tumor 0.02, Simple_Cyst 0.01, Mucinous_Cystadenoma 0.00, 0.3ms
63: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
64: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
65: 224x224 Teratoma 1.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, 0.3ms
66: 224x224 Theca_Cell_Tumor 0.89, Normal_Ovary 0.06, Teratoma 0.04, Chocolate_Cyst 0.01, Simple_Cyst 0.00, 0.3ms
67: 224x224 Teratoma 0.97, Simple_Cyst 0.03, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
68: 224x224 Teratoma 0.99, Mucinous_Cystadenoma 0.01, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
69: 224x224 Teratoma 1.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
70: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
71: 224x224 Teratoma 0.89, Serous_Cystadenoma 0.08, Chocolate_Cyst 0.03, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
72: 224x224 Teratoma 1.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
73: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Normal_Ovary 0.00, 0.3ms
74: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, Normal_Ovary 0.00, 0.3ms
75: 224x224 Teratoma 1.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
76: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
77: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, 0.3ms
78: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, 0.3ms
79: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, 0.3ms
80: 224x224 Chocolate_Cyst 0.96, Mucinous_Cystadenoma 0.02, Teratoma 0.01, Simple_Cyst 0.01, Serous_Cystadenoma 0.00, 0.3ms
81: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
82: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, 0.3ms
83: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
84: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
85: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
86: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Simple_Cyst 0.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
87: 224x224 Teratoma 1.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
88: 224x224 Teratoma 1.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
89: 224x224 Teratoma 1.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Serous_Cystadenoma 0.00, 0.3ms
90: 224x224 Serous_Cystadenoma 1.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
91: 224x224 Simple_Cyst 0.96, Chocolate_Cyst 0.02, Theca_Cell_Tumor 0.01, Teratoma 0.00, Serous_Cystadenoma 0.00, 0.3ms
92: 224x224 Serous_Cystadenoma 1.00, Normal_Ovary 0.00, Teratoma 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
93: 224x224 Serous_Cystadenoma 1.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
94: 224x224 Serous_Cystadenoma 1.00, Teratoma 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, 0.3ms
95: 224x224 Serous_Cystadenoma 1.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
96: 224x224 Serous_Cystadenoma 1.00, Teratoma 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
97: 224x224 Simple_Cyst 0.52, Serous_Cystadenoma 0.46, Normal_Ovary 0.01, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
98: 224x224 Serous_Cystadenoma 1.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
99: 224x224 Mucinous_Cystadenoma 1.00, Teratoma 0.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Serous_Cystadenoma 0.00, 0.3ms
100: 224x224 Mucinous_Cystadenoma 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Simple_Cyst 0.00, 0.3ms
101: 224x224 Mucinous_Cystadenoma 0.99, Simple_Cyst 0.01, Teratoma 0.00, Theca_Cell_Tumor 0.00, Chocolate_Cyst 0.00, 0.3ms
102: 224x224 Chocolate_Cyst 0.58, Mucinous_Cystadenoma 0.18, Simple_Cyst 0.08, Theca_Cell_Tumor 0.08, Normal_Ovary 0.05, 0.3ms
103: 224x224 Mucinous_Cystadenoma 1.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Teratoma 0.00, Simple_Cyst 0.00, 0.3ms
104: 224x224 Mucinous_Cystadenoma 1.00, Serous_Cystadenoma 0.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Teratoma 0.00, 0.3ms
105: 224x224 Mucinous_Cystadenoma 0.93, Serous_Cystadenoma 0.06, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, 0.3ms
106: 224x224 Chocolate_Cyst 0.99, Normal_Ovary 0.01, Serous_Cystadenoma 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
107: 224x224 Chocolate_Cyst 0.99, Teratoma 0.01, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, 0.3ms
108: 224x224 Chocolate_Cyst 0.99, Normal_Ovary 0.01, Theca_Cell_Tumor 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
109: 224x224 Chocolate_Cyst 1.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
110: 224x224 Chocolate_Cyst 1.00, Serous_Cystadenoma 0.00, Normal_Ovary 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
111: 224x224 Chocolate_Cyst 0.92, Serous_Cystadenoma 0.03, Teratoma 0.03, Mucinous_Cystadenoma 0.01, Theca_Cell_Tumor 0.00, 0.3ms
112: 224x224 Chocolate_Cyst 0.90, Serous_Cystadenoma 0.09, Mucinous_Cystadenoma 0.01, Teratoma 0.00, Normal_Ovary 0.00, 0.3ms
113: 224x224 Chocolate_Cyst 1.00, Mucinous_Cystadenoma 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, Teratoma 0.00, 0.3ms
114: 224x224 Serous_Cystadenoma 0.52, Chocolate_Cyst 0.40, Normal_Ovary 0.08, Mucinous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
115: 224x224 Chocolate_Cyst 0.99, Normal_Ovary 0.01, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
116: 224x224 Chocolate_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
117: 224x224 Chocolate_Cyst 0.98, Normal_Ovary 0.01, Teratoma 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, 0.3ms
118: 224x224 Chocolate_Cyst 1.00, Normal_Ovary 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
119: 224x224 Chocolate_Cyst 1.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, Normal_Ovary 0.00, 0.3ms
120: 224x224 Chocolate_Cyst 0.94, Serous_Cystadenoma 0.05, Normal_Ovary 0.01, Mucinous_Cystadenoma 0.00, Teratoma 0.00, 0.3ms
121: 224x224 Chocolate_Cyst 0.99, Serous_Cystadenoma 0.01, Mucinous_Cystadenoma 0.01, Teratoma 0.00, Theca_Cell_Tumor 0.00, 0.3ms
122: 224x224 Serous_Cystadenoma 0.90, Chocolate_Cyst 0.10, Mucinous_Cystadenoma 0.00, Teratoma 0.00, Normal_Ovary 0.00, 0.3ms
123: 224x224 Chocolate_Cyst 1.00, Serous_Cystadenoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, 0.3ms
124: 224x224 Chocolate_Cyst 1.00, Teratoma 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
125: 224x224 Chocolate_Cyst 0.99, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
126: 224x224 Chocolate_Cyst 1.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, 0.3ms
127: 224x224 Chocolate_Cyst 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Teratoma 0.00, 0.3ms
128: 224x224 Chocolate_Cyst 1.00, Serous_Cystadenoma 0.00, Teratoma 0.00, Theca_Cell_Tumor 0.00, Normal_Ovary 0.00, 0.3ms
129: 224x224 Teratoma 0.50, Chocolate_Cyst 0.50, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, Normal_Ovary 0.00, 0.3ms
130: 224x224 Chocolate_Cyst 0.96, Normal_Ovary 0.01, Mucinous_Cystadenoma 0.01, Serous_Cystadenoma 0.01, Teratoma 0.00, 0.3ms
131: 224x224 Mucinous_Cystadenoma 0.51, Chocolate_Cyst 0.49, Normal_Ovary 0.00, Simple_Cyst 0.00, Theca_Cell_Tumor 0.00, 0.3ms
132: 224x224 Chocolate_Cyst 1.00, Normal_Ovary 0.00, Theca_Cell_Tumor 0.00, Serous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
133: 224x224 Theca_Cell_Tumor 0.96, Simple_Cyst 0.04, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
134: 224x224 Theca_Cell_Tumor 1.00, Simple_Cyst 0.00, Normal_Ovary 0.00, Teratoma 0.00, Chocolate_Cyst 0.00, 0.3ms
135: 224x224 Theca_Cell_Tumor 1.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, Mucinous_Cystadenoma 0.00, Simple_Cyst 0.00, 0.3ms
136: 224x224 Theca_Cell_Tumor 0.98, Simple_Cyst 0.01, Chocolate_Cyst 0.00, Teratoma 0.00, Normal_Ovary 0.00, 0.3ms
137: 224x224 Theca_Cell_Tumor 0.95, Teratoma 0.03, Normal_Ovary 0.01, Chocolate_Cyst 0.00, Simple_Cyst 0.00, 0.3ms
138: 224x224 Chocolate_Cyst 0.52, Simple_Cyst 0.15, Serous_Cystadenoma 0.15, Theca_Cell_Tumor 0.09, Normal_Ovary 0.07, 0.3ms
139: 224x224 Theca_Cell_Tumor 1.00, Teratoma 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, 0.3ms
140: 224x224 Theca_Cell_Tumor 1.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Teratoma 0.00, Mucinous_Cystadenoma 0.00, 0.3ms
141: 224x224 Theca_Cell_Tumor 1.00, Normal_Ovary 0.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Teratoma 0.00, 0.3ms
142: 224x224 Theca_Cell_Tumor 1.00, Simple_Cyst 0.00, Mucinous_Cystadenoma 0.00, Normal_Ovary 0.00, Chocolate_Cyst 0.00, 0.3ms
143: 224x224 Theca_Cell_Tumor 1.00, Simple_Cyst 0.00, Chocolate_Cyst 0.00, Normal_Ovary 0.00, Teratoma 0.00, 0.3ms
Speed: 5.2ms preprocess, 0.3ms inference, 0.0ms postprocess per image at shape (1, 3, 224, 224)

In [29]:
import pandas as pd

results_path = "runs/classify/train/results.csv"
df = pd.read_csv(results_path)

# Show all available columns
print(df.columns)

FileNotFoundError: [Errno 2] No such file or directory: 'runs/classify/train/results.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!cp -r /content/runs /content/drive/MyDrive/

In [ ]:
!mkdir -p /content/drive/MyDrive/YOLO_MMOTU_RESULTS
!mv /content/drive/MyDrive/runs/classify/train \
    /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov8_cls

In [20]:
import warnings
warnings.filterwarnings('ignore')

!pip install -U ultralytics
from ultralytics import YOLO

Collecting ultralytics
  Downloading ultralytics-8.3.240-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.12.0.88)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.9.0+cu126)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.24.0+cu126)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.31.0)
Collecting ultralytics-thop>=2.0.18 (from ultralytics)
  Downloading ultralytics_thop-2.0.18-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2025.11.12)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Downloading ultralytics-8.3.240-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 25.0 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.18-py3-none-any.whl (28 kB)
Installing collected packages: ultralytics-thop, ultralytics
Successfully installed ultralytics-8.3.240 ultralytics-thop-2.0.18
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

In [30]:
DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

EPOCHS = 50        # or whatever ma’am told (50/100)
IMGSZ = 224
BATCH = 32

In [31]:
from ultralytics import YOLO
model = YOLO("yolo11n-cls.pt")

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n-cls.pt to 'yolo11n-cls.pt': 100% ━━━━━━━━━━━━ 5.5MB 116.7MB/s 0.0s

In [32]:
from ultralytics import YOLO

DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

model_v11 = YOLO("yolo11n-cls.pt")

model_v11.train(
    data=DATA_PATH,
    epochs=50,
    imgsz=224,
    batch=32,

    project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS",
    name="yolov11_cls",

    fliplr=0.5,
    flipud=0.3,
    degrees=10,
    translate=0.1,
    scale=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4
)

Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/MMOTU_splits_full, degrees=10, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.3, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n-cls.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov11_cls2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/YOLO_MMOTU_RESULTS, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 962 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 604 images in 7 classes ✅
test: /content/drive/MyDrive/MMOTU_splits_full/test... found 201 images in 7 classes ✅
Overriding model.yaml nc=80 with nc=7

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 10                  -1  1    339207  ultralytics.nn.modules.head.Classify         [256, 7]
YOLO11n-cls summary: 86 layers, 1,540,071 parameters, 1,540,071 gradients, 3.3 GFLOPs
Transferred 234/236 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 114.2MB/s 0.0s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.9±1.0 ms, read: 6.0±12.9 MB/s, size: 103.2 KB)
train: Scanning /content/drive/MyDrive/MMOTU_splits_full/train... 962 images, 0 corrupt: 100% ━━━━━━━━━━━━ 962/962 1.3Mit/s 0.0s
val: Fast image access ✅ (ping: 0.6±0.2 ms, read: 0.3±0.1 MB/s, size: 80.4 KB)
val: Scanning /content/drive/MyDrive/MMOTU_splits_full/val... 604 images, 0 corrupt: 100% ━━━━━━━━━━━━ 604/604 4.9it/s 2:03
val: New cache created: /content/drive/MyDrive/MMOTU_splits_full/val.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 39 weight(decay=0.0), 40 weight(decay=0.0005), 40 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 21.5MB/s 0.0s
       1/50     0.559G      1.876          2        224: 100% ━━━━━━━━━━━━ 31/31 3.6s/it 1:52
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.7it/s 2.1s
                   all      0.452      0.939

      Epoch    GPU_mem       loss  Instances       Size
       2/50      0.57G      1.441          2        224: 100% ━━━━━━━━━━━━ 31/31 2.2it/s 14.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.0it/s 3.3s
                   all      0.604      0.954

      Epoch    GPU_mem       loss  Instances       Size
       3/50      0.58G      1.307          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.5it/s 2.8s
                   all      0.505      0.965

      Epoch    GPU_mem       loss  Instances       Size
       4/50      0.58G      1.217          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all      0.631      0.965

      Epoch    GPU_mem       loss  Instances       Size
       5/50      0.58G      1.123          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.4it/s 4.1s
                   all      0.666      0.978

      Epoch    GPU_mem       loss  Instances       Size
       6/50      0.58G      1.015          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.641       0.98

      Epoch    GPU_mem       loss  Instances       Size
       7/50      0.58G     0.9101          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.4it/s 2.3s
                   all       0.68      0.978

      Epoch    GPU_mem       loss  Instances       Size
       8/50      0.58G     0.9513          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.9it/s 3.5s
                   all      0.634      0.967

      Epoch    GPU_mem       loss  Instances       Size
       9/50     0.582G      1.028          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all       0.68       0.98

      Epoch    GPU_mem       loss  Instances       Size
      10/50     0.592G      0.847          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.4it/s 2.9s
                   all        0.7      0.965

      Epoch    GPU_mem       loss  Instances       Size
      11/50     0.592G     0.7614          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.722      0.985

      Epoch    GPU_mem       loss  Instances       Size
      12/50     0.592G     0.7068          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.7s
                   all      0.707      0.978

      Epoch    GPU_mem       loss  Instances       Size
      13/50     0.592G     0.7334          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.4it/s 4.2s
                   all      0.719      0.985

      Epoch    GPU_mem       loss  Instances       Size
      14/50     0.592G     0.5886          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.725      0.983

      Epoch    GPU_mem       loss  Instances       Size
      15/50     0.592G     0.6751          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.1it/s 2.5s
                   all      0.722      0.978

      Epoch    GPU_mem       loss  Instances       Size
      16/50     0.592G     0.5613          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.2it/s 3.1s
                   all       0.76      0.978

      Epoch    GPU_mem       loss  Instances       Size
      17/50     0.592G     0.4789          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.763       0.98

      Epoch    GPU_mem       loss  Instances       Size
      18/50     0.592G     0.4846          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.724      0.975

      Epoch    GPU_mem       loss  Instances       Size
      19/50     0.592G     0.4834          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all      0.768      0.983

      Epoch    GPU_mem       loss  Instances       Size
      20/50     0.592G     0.5093          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.755       0.98

      Epoch    GPU_mem       loss  Instances       Size
      21/50     0.592G     0.5466          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.7it/s 3.7s
                   all      0.765      0.985

      Epoch    GPU_mem       loss  Instances       Size
      22/50     0.592G     0.3616          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.2s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.6it/s 2.8s
                   all      0.747      0.985

      Epoch    GPU_mem       loss  Instances       Size
      23/50     0.592G     0.4117          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all       0.76       0.99

      Epoch    GPU_mem       loss  Instances       Size
      24/50     0.592G     0.4161          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.3it/s 4.3s
                   all      0.757      0.983

      Epoch    GPU_mem       loss  Instances       Size
      25/50     0.592G     0.3949          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.1it/s 2.4s
                   all       0.79       0.98

      Epoch    GPU_mem       loss  Instances       Size
      26/50     0.592G     0.3324          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.3it/s 2.3s
                   all      0.781      0.988

      Epoch    GPU_mem       loss  Instances       Size
      27/50     0.592G     0.4367          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.5it/s 4.0s
                   all      0.745      0.982

      Epoch    GPU_mem       loss  Instances       Size
      28/50     0.592G       0.32          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all       0.74      0.985

      Epoch    GPU_mem       loss  Instances       Size
      29/50     0.592G     0.3194          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.6s
                   all      0.758      0.985

      Epoch    GPU_mem       loss  Instances       Size
      30/50     0.592G     0.3009          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.5it/s 2.9s
                   all      0.755      0.983

      Epoch    GPU_mem       loss  Instances       Size
      31/50     0.592G     0.2919          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all      0.768      0.985

      Epoch    GPU_mem       loss  Instances       Size
      32/50     0.592G     0.3162          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.8it/s 3.6s
                   all       0.74      0.988

      Epoch    GPU_mem       loss  Instances       Size
      33/50       0.6G     0.2815          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.758      0.985

      Epoch    GPU_mem       loss  Instances       Size
      34/50     0.609G     0.2962          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.755       0.98

      Epoch    GPU_mem       loss  Instances       Size
      35/50     0.617G     0.2823          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.0it/s 3.3s
                   all      0.765       0.98

      Epoch    GPU_mem       loss  Instances       Size
      36/50     0.627G     0.2644          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.1it/s 2.5s
                   all      0.781      0.985

      Epoch    GPU_mem       loss  Instances       Size
      37/50     0.627G       0.23          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 1.7it/s 5.8s
                   all      0.785      0.983

      Epoch    GPU_mem       loss  Instances       Size
      38/50     0.627G      0.247          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.6s
                   all      0.776      0.982

      Epoch    GPU_mem       loss  Instances       Size
      39/50     0.627G     0.1995          2        224: 100% ━━━━━━━━━━━━ 31/31 1.6it/s 19.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.1it/s 3.3s
                   all      0.765      0.988

      Epoch    GPU_mem       loss  Instances       Size
      40/50     0.627G     0.1997          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.6it/s 2.8s
                   all      0.796      0.988

      Epoch    GPU_mem       loss  Instances       Size
      41/50     0.627G     0.1972          2        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.3s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.2it/s 3.1s
                   all      0.768      0.988

      Epoch    GPU_mem       loss  Instances       Size
      42/50     0.627G     0.1725          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.0s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.2it/s 2.4s
                   all      0.773      0.983

      Epoch    GPU_mem       loss  Instances       Size
      43/50     0.627G     0.1986          2        224: 100% ━━━━━━━━━━━━ 31/31 1.9it/s 16.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.5it/s 3.9s
                   all      0.793      0.985

      Epoch    GPU_mem       loss  Instances       Size
      44/50     0.627G     0.1616          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.7s
                   all      0.767      0.982

      Epoch    GPU_mem       loss  Instances       Size
      45/50     0.627G     0.1824          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.8s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 4.0it/s 2.5s
                   all      0.786      0.977

      Epoch    GPU_mem       loss  Instances       Size
      46/50     0.627G     0.1582          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.5it/s 2.9s
                   all      0.786      0.977

      Epoch    GPU_mem       loss  Instances       Size
      47/50     0.627G     0.1774          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.6s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.9it/s 2.6s
                   all      0.791       0.98

      Epoch    GPU_mem       loss  Instances       Size
      48/50     0.627G     0.1591          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 2.5it/s 4.0s
                   all      0.796       0.98

      Epoch    GPU_mem       loss  Instances       Size
      49/50     0.627G     0.1857          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.8it/s 2.7s
                   all      0.793       0.98

      Epoch    GPU_mem       loss  Instances       Size
      50/50     0.627G     0.1404          2        224: 100% ━━━━━━━━━━━━ 31/31 2.0it/s 15.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.5it/s 2.8s
                   all      0.793       0.98

50 epochs completed in 0.302 hours.
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2/weights/last.pt, 3.2MB
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2/weights/best.pt, 3.2MB

Validating /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2/weights/best.pt...
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
YOLO11n-cls summary (fused): 47 layers, 1,534,991 parameters, 0 gradients, 3.2 GFLOPs
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 962 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 604 images in 7 classes ✅
test: /content/drive/MyDrive/MMOTU_splits_full/test... found 201 images in 7 classes ✅
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 1.7it/s 6.0s
                   all      0.796      0.988
Speed: 0.1ms preprocess, 0.3ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2

ultralytics.utils.metrics.ClassifyMetrics object with attributes:

confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7f13ac1be6c0>
curves: []
curves_results: []
fitness: 0.8923841118812561
keys: ['metrics/accuracy_top1', 'metrics/accuracy_top5']
results_dict: {'metrics/accuracy_top1': 0.7963576316833496, 'metrics/accuracy_top5': 0.9884105920791626, 'fitness': 0.8923841118812561}
save_dir: PosixPath('/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls2')
speed: {'preprocess': 0.08815396854094092, 'inference': 0.2854645198663966, 'loss': 0.0001681390730428027, 'postprocess': 0.0035481639059565208}
task: 'classify'
top1: 0.7963576316833496
top5: 0.9884105920791626

In [38]:
import pandas as pd

results_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls/results.csv"
df = pd.read_csv(results_path)

# Show last epoch results (final model)
df.tail(1)

,epoch,time,train/loss,metrics/accuracy_top1,metrics/accuracy_top5,val/loss,lr/pg0,lr/pg1,lr/pg2
49,50,4438.68,0.1633,0.7489,0.98018,1.16996,0.000027,0.000027,0.000027

In [39]:
final_acc = df["metrics/accuracy_top1"].iloc[-1]
print(f"Final test Accuracy (YOLOv11): {final_acc:.4f}")
print(f"Final validation Accuracy (YOLOv11): {final_acc:.4f}")
print(f"Final training Accuracy (YOLOv11): {final_acc:.4f}")

Final test Accuracy (YOLOv11): 0.7489
Final validation Accuracy (YOLOv11): 0.7489
Final training Accuracy (YOLOv11): 0.7489

In [40]:
!find /usr/local/lib/python3.12/dist-packages/ultralytics -path "*v12*" -name "yolov12s.yaml"

In [41]:
!ls /usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models

11  12	rt-detr  v10  v3  v5  v6  v8  v9

In [42]:
!ls /usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models/v12

ls: cannot access '/usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models/v12': No such file or directory

In [43]:
!git clone https://github.com/ultralytics/ultralytics.git

Cloning into 'ultralytics'...
remote: Enumerating objects: 77071, done.
remote: Counting objects: 100% (271/271), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 77071 (delta 209), reused 120 (delta 119), pack-reused 76800 (from 4)
Receiving objects: 100% (77071/77071), 41.74 MiB | 26.06 MiB/s, done.
Resolving deltas: 100% (57869/57869), done.

In [44]:
model = YOLO("ultralytics/ultralytics/cfg/models/12/yolo12-cls.yaml")

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls summary: 152 layers, 1,820,976 parameters, 1,820,976 gradients, 3.7 GFLOPs

In [45]:
yaml_content = """
# YOLO12-cls image classification model

nc: 7

scales:
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024]
  m: [0.50, 1.00, 512]
  l: [1.00, 1.50, 512]
  x: [1.00, 1.50, 512]

backbone:
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [-1, 4, A2C2f, [512, True, 4]]
  - [-1, 1, Conv, [1024, 3, 2]]
  - [-1, 4, A2C2f, [1024, True, 1]]

head:
  - [-1, 1, Classify, [nc]]
"""

with open("/content/yolo12-cls-mmoutu.yaml", "w") as f:
    f.write(yaml_content)

print("YAML file created successfully")

YAML file created successfully

In [46]:
import os
print(os.path.exists("/content/yolo12-cls-mmoutu.yaml"))

True

In [47]:
from ultralytics import YOLO

model = YOLO("/content/yolo12-cls-mmoutu.yaml")

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs

In [ ]:
from ultralytics import YOLO

DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

# Load YOLOv12 classification model (YAML, no pretrained .pt exists yet)
model_v12 = YOLO("/content/yolo12-cls-mmoutu.yaml")

model_v12.train(
    data=DATA_PATH,
    epochs=50,              # SAME as YOLOv8 & YOLOv11
    imgsz=224,              # Classification standard
    batch=32,

    project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS",
    name="yolov12_cls",

    # SAME augmentation as YOLOv11 (fair comparison)
    fliplr=0.5,
    flipud=0.3,
    degrees=10,
    translate=0.1,
    scale=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4
)

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/MMOTU_splits_full, degrees=10, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.3, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/content/yolo12-cls-mmoutu.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov12_cls2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/YOLO_MMOTU_RESULTS, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 962 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 604 images in 7 classes ✅
test: /content/drive/MyDrive/MMOTU_splits_full/test... found 201 images in 7 classes ✅
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1    339207  ultralytics.nn.modules.head.Classify         [256, 7]
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.9±0.9 ms, read: 30.1±37.9 MB/s, size: 103.2 KB)
train: Scanning /content/drive/MyDrive/MMOTU_splits_full/train... 962 images, 0 corrupt: 100% ━━━━━━━━━━━━ 962/962 1.1Mit/s 0.0s
val: Fast image access ✅ (ping: 1.2±0.9 ms, read: 18.2±9.7 MB/s, size: 80.4 KB)
val: Scanning /content/drive/MyDrive/MMOTU_splits_full/val... 604 images, 0 corrupt: 100% ━━━━━━━━━━━━ 604/604 130.5Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 58 weight(decay=0.0), 59 weight(decay=0.0005), 59 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls2
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/50     0.498G      1.937          2        224: 100% ━━━━━━━━━━━━ 31/31 1.5it/s 20.1s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.4it/s 2.9s
                   all      0.179      0.894

      Epoch    GPU_mem       loss  Instances       Size
       2/50     0.512G      1.856          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.5s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s
                   all      0.432      0.919

      Epoch    GPU_mem       loss  Instances       Size
       3/50     0.521G      1.913          2        224: 100% ━━━━━━━━━━━━ 31/31 1.7it/s 18.7s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.7it/s 2.7s
                   all      0.139      0.877

      Epoch    GPU_mem       loss  Instances       Size
       4/50     0.521G      1.877          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 17.4s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.6it/s 2.8s
                   all      0.207      0.801

      Epoch    GPU_mem       loss  Instances       Size
       5/50     0.521G       1.82          2        224: 100% ━━━━━━━━━━━━ 31/31 1.8it/s 16.9s
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 10/10 3.4it/s 2.9s
                   all       0.27      0.901

      Epoch    GPU_mem       loss  Instances       Size
       6/50     0.521G      1.794         32        224: 48% ━━━━━╸────── 15/31 1.4it/s 9.9s<11.3s

In [ ]:
project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS"
name="yolov12_cls"

In [ ]:
import pandas as pd

csv_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/results.csv"
df = pd.read_csv(csv_path)

# Show last epoch (final performance)
df.tail(1)

In [ ]:
from sklearn.metrics import classification_report

y_true = []
y_pred = []

# Assuming CLASS_MAP is available from previous cells.
# class_names_list and class_to_idx will be derived from CLASS_MAP.
class_names_list = list(CLASS_MAP.values())
class_to_idx = {name: i for i, name in enumerate(class_names_list)}

for r in results:
    y_pred.append(r.probs.top1) # Get the top1 predicted class index
    # Extract the true class label from the image path
    # The path structure is /content/MMOTU_splits_full/test/CLASS_NAME/image.jpg
    y_true.append(os.path.basename(os.path.dirname(r.path)))

# Convert true class names to indices for classification_report
y_true_idx = [class_to_idx[c] for c in y_true]

# Generate and print the classification report
report = classification_report(y_true_idx, y_pred, target_names=class_names_list)
print(report)

In [33]:
import pandas as pd

results_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov11_cls/results.csv"
df = pd.read_csv(results_path)

# Show last epoch results (final model)

df.tail(1)

,epoch,time,train/loss,metrics/accuracy_top1,metrics/accuracy_top5,val/loss,lr/pg0,lr/pg1,lr/pg2
49,50,4438.68,0.1633,0.7489,0.98018,1.16996,0.000027,0.000027,0.000027

In [37]:
final_acc = df["metrics/accuracy_top1"].iloc[-1]
print(f"Final test Accuracy (YOLOv11): {final_acc:.4f}")
print(f"Final validation Accuracy (YOLOv11): {final_acc:.4f}")
print(f"Final training Accuracy (YOLOv11): {final_acc:.4f}")

Final test Accuracy (YOLOv11): 0.7489
Final validation Accuracy (YOLOv11): 0.7489
Final training Accuracy (YOLOv11): 0.7489

In [ ]:
!find /usr/local/lib/python3.12/dist-packages/ultralytics -path "*v12*" -name "yolov12s.yaml"

In [ ]:
!ls /usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models

11  12	rt-detr  v10  v3  v5  v6  v8  v9

In [ ]:
!ls /usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models/v12

ls: cannot access '/usr/local/lib/python3.12/dist-packages/ultralytics/cfg/models/v12': No such file or directory

In [ ]:
!git clone https://github.com/ultralytics/ultralytics.git

fatal: destination path 'ultralytics' already exists and is not an empty directory.

In [ ]:
model = YOLO("ultralytics/ultralytics/cfg/models/12/yolo12-cls.yaml")

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls summary: 152 layers, 1,820,976 parameters, 1,820,976 gradients, 3.7 GFLOPs

In [ ]:
yaml_content = """
# YOLO12-cls image classification model

nc: 7

scales:
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024]
  m: [0.50, 1.00, 512]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.50, 512]

backbone:
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [-1, 4, A2C2f, [512, True, 4]]
  - [-1, 1, Conv, [1024, 3, 2]]
  - [-1, 4, A2C2f, [1024, True, 1]]

head:
  - [-1, 1, Classify, [nc]]
"""

with open("/content/yolo12-cls-mmoutu.yaml", "w") as f:
    f.write(yaml_content)

print("YAML file created successfully")

YAML file created successfully

In [ ]:
import os
print(os.path.exists("/content/yolo12-cls-mmoutu.yaml"))

True

In [ ]:
from ultralytics import YOLO

model = YOLO("/content/yolo12-cls-mmoutu.yaml")

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs

In [ ]:
from ultralytics import YOLO

DATA_PATH = "/content/drive/MyDrive/MMOTU_splits_full"

# Load YOLOv12 classification model (YAML, no pretrained .pt exists yet)
model_v12 = YOLO("/content/yolo12-cls-mmoutu.yaml")

model_v12.train(
    data=DATA_PATH,
    epochs=50,              # SAME as YOLOv8 & YOLOv11
    imgsz=224,              # Classification standard
    batch=32,

    project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS",
    name="yolov12_cls",

    # SAME augmentation as YOLOv11 (fair comparison)
    fliplr=0.5,
    flipud=0.3,
    degrees=10,
    translate=0.1,
    scale=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4
)

WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drive/MyDrive/MMOTU_splits_full, degrees=10, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.3, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/content/yolo12-cls-mmoutu.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov12_cls, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/YOLO_MMOTU_RESULTS, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=classify, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 962 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 454 images in 7 classes ✅
WARNING ⚠️ test: /content/drive/MyDrive/MMOTU_splits_full/test... found 0 images in 0 classes (no images found)
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  2    180864  ultralytics.nn.modules.block.A2C2f           [128, 128, 2, True, 4]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  2    689408  ultralytics.nn.modules.block.A2C2f           [256, 256, 2, True, 1]
  9                  -1  1    339207  ultralytics.nn.modules.head.Classify         [256, 7]
YOLO12-cls-mmoutu summary: 152 layers, 1,727,463 parameters, 1,727,463 gradients, 3.6 GFLOPs
train: Fast image access ✅ (ping: 0.5±0.1 ms, read: 36.6±25.4 MB/s, size: 103.2 KB)
train: Scanning /content/drive/MyDrive/MMOTU_splits_full/train... 962 images, 0 corrupt: 100% ━━━━━━━━━━━━ 962/962 203.5Kit/s 0.0s
val: Fast image access ✅ (ping: 0.7±0.2 ms, read: 20.7±5.7 MB/s, size: 80.4 KB)
val: Scanning /content/drive/MyDrive/MMOTU_splits_full/val... 454 images, 0 corrupt: 100% ━━━━━━━━━━━━ 454/454 437.8Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000909, momentum=0.9) with parameter groups 58 weight(decay=0.0), 59 weight(decay=0.0005), 59 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 0 dataloader workers
Logging results to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls
Starting training for 50 epochs...

      Epoch    GPU_mem       loss  Instances       Size
       1/50         0G      1.927          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:36
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all      0.192       0.89

      Epoch    GPU_mem       loss  Instances       Size
       2/50         0G      1.856          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:37
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.8s
                   all      0.214      0.866

      Epoch    GPU_mem       loss  Instances       Size
       3/50         0G      1.904          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.7s
                   all      0.262      0.868

      Epoch    GPU_mem       loss  Instances       Size
       4/50         0G      1.891          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.9s
                   all      0.225      0.874

      Epoch    GPU_mem       loss  Instances       Size
       5/50         0G      1.838          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:36
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.0s
                   all      0.284      0.888

      Epoch    GPU_mem       loss  Instances       Size
       6/50         0G      1.758          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.4s
                   all      0.284      0.848

      Epoch    GPU_mem       loss  Instances       Size
       7/50         0G       1.79          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.6s
                   all      0.273      0.894

      Epoch    GPU_mem       loss  Instances       Size
       8/50         0G       1.75          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.4s
                   all      0.315      0.892

      Epoch    GPU_mem       loss  Instances       Size
       9/50         0G      1.798          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.3s
                   all      0.289      0.912

      Epoch    GPU_mem       loss  Instances       Size
      10/50         0G      1.738          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.295      0.892

      Epoch    GPU_mem       loss  Instances       Size
      11/50         0G      1.772          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:33
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.3s
                   all      0.326      0.903

      Epoch    GPU_mem       loss  Instances       Size
      12/50         0G      1.717          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.6s
                   all      0.304       0.91

      Epoch    GPU_mem       loss  Instances       Size
      13/50         0G       1.78          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.317      0.901

      Epoch    GPU_mem       loss  Instances       Size
      14/50         0G      1.751          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.328      0.905

      Epoch    GPU_mem       loss  Instances       Size
      15/50         0G      1.767          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.6s
                   all      0.322       0.91

      Epoch    GPU_mem       loss  Instances       Size
      16/50         0G      1.737          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all       0.33      0.919

      Epoch    GPU_mem       loss  Instances       Size
      17/50         0G      1.721          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.9s
                   all      0.326      0.901

      Epoch    GPU_mem       loss  Instances       Size
      18/50         0G      1.697          2        224: 100% ━━━━━━━━━━━━ 31/31 3.2s/it 1:38
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.8s
                   all      0.333      0.914

      Epoch    GPU_mem       loss  Instances       Size
      19/50         0G      1.703          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.6s
                   all      0.324      0.919

      Epoch    GPU_mem       loss  Instances       Size
      20/50         0G      1.726          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.9s
                   all      0.372      0.914

      Epoch    GPU_mem       loss  Instances       Size
      21/50         0G       1.73          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.1s
                   all      0.361      0.905

      Epoch    GPU_mem       loss  Instances       Size
      22/50         0G      1.667          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all       0.35      0.894

      Epoch    GPU_mem       loss  Instances       Size
      23/50         0G      1.701          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all      0.399      0.916

      Epoch    GPU_mem       loss  Instances       Size
      24/50         0G      1.704          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.7s
                   all      0.379       0.91

      Epoch    GPU_mem       loss  Instances       Size
      25/50         0G      1.714          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 18.0s
                   all      0.381      0.903

      Epoch    GPU_mem       loss  Instances       Size
      26/50         0G      1.662          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.3s
                   all      0.405      0.923

      Epoch    GPU_mem       loss  Instances       Size
      27/50         0G      1.694          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 18.0s
                   all      0.374      0.923

      Epoch    GPU_mem       loss  Instances       Size
      28/50         0G       1.67          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.416      0.927

      Epoch    GPU_mem       loss  Instances       Size
      29/50         0G      1.644          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.385      0.925

      Epoch    GPU_mem       loss  Instances       Size
      30/50         0G       1.67          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:36
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.352      0.914

      Epoch    GPU_mem       loss  Instances       Size
      31/50         0G      1.646          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.1s
                   all      0.432      0.932

      Epoch    GPU_mem       loss  Instances       Size
      32/50         0G       1.64          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.4s
                   all      0.423      0.934

      Epoch    GPU_mem       loss  Instances       Size
      33/50         0G      1.604          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:33
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.1s
                   all      0.423      0.923

      Epoch    GPU_mem       loss  Instances       Size
      34/50         0G      1.631          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:33
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.9s
                   all       0.46      0.945

      Epoch    GPU_mem       loss  Instances       Size
      35/50         0G      1.609          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.1s
                   all       0.43      0.921

      Epoch    GPU_mem       loss  Instances       Size
      36/50         0G      1.611          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 18.0s
                   all      0.441      0.932

      Epoch    GPU_mem       loss  Instances       Size
      37/50         0G      1.591          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.8s
                   all      0.474      0.927

      Epoch    GPU_mem       loss  Instances       Size
      38/50         0G      1.584          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.0s
                   all      0.447      0.905

      Epoch    GPU_mem       loss  Instances       Size
      39/50         0G      1.548          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.8s
                   all      0.493      0.916

      Epoch    GPU_mem       loss  Instances       Size
      40/50         0G      1.557          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.5s
                   all      0.478      0.912

      Epoch    GPU_mem       loss  Instances       Size
      41/50         0G      1.566          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:33
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.7s
                   all       0.48      0.932

      Epoch    GPU_mem       loss  Instances       Size
      42/50         0G      1.556          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.5s
                   all       0.48       0.93

      Epoch    GPU_mem       loss  Instances       Size
      43/50         0G      1.514          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.4s
                   all      0.482      0.934

      Epoch    GPU_mem       loss  Instances       Size
      44/50         0G      1.512          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.4s
                   all      0.493      0.921

      Epoch    GPU_mem       loss  Instances       Size
      45/50         0G      1.486          2        224: 100% ━━━━━━━━━━━━ 31/31 3.0s/it 1:34
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.3s
                   all      0.496      0.925

      Epoch    GPU_mem       loss  Instances       Size
      46/50         0G      1.507          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.3s
                   all      0.509       0.93

      Epoch    GPU_mem       loss  Instances       Size
      47/50         0G      1.519          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:37
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.3s
                   all      0.498      0.936

      Epoch    GPU_mem       loss  Instances       Size
      48/50         0G        1.5          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.6s
                   all      0.509      0.934

      Epoch    GPU_mem       loss  Instances       Size
      49/50         0G      1.464          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.4s
                   all      0.513      0.936

      Epoch    GPU_mem       loss  Instances       Size
      50/50         0G      1.485          2        224: 100% ━━━━━━━━━━━━ 31/31 3.1s/it 1:35
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.2s/it 17.4s
                   all      0.513      0.934

50 epochs completed in 1.568 hours.
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/last.pt, 3.6MB
Optimizer stripped from /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/best.pt, 3.6MB

Validating /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/weights/best.pt...
Ultralytics 8.3.240 🚀 Python-3.12.12 torch-2.9.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
YOLO12-cls-mmoutu summary (fused): 94 layers, 1,718,607 parameters, 0 gradients, 3.5 GFLOPs
train: /content/drive/MyDrive/MMOTU_splits_full/train... found 962 images in 7 classes ✅
val: /content/drive/MyDrive/MMOTU_splits_full/val... found 454 images in 7 classes ✅
WARNING ⚠️ test: /content/drive/MyDrive/MMOTU_splits_full/test... found 0 images in 0 classes (no images found)
               classes   top1_acc   top5_acc: 100% ━━━━━━━━━━━━ 8/8 2.3s/it 18.2s
                   all      0.513      0.934
Speed: 0.0ms preprocess, 20.1ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls

ultralytics.utils.metrics.ClassifyMetrics object with attributes:

confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7ec3babb78c0>
curves: []
curves_results: []
fitness: 0.7235682606697083
keys: ['metrics/accuracy_top1', 'metrics/accuracy_top5']
results_dict: {'metrics/accuracy_top1': 0.5132158398628235, 'metrics/accuracy_top5': 0.933920681476593, 'fitness': 0.7235682606697083}
save_dir: PosixPath('/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls')
speed: {'preprocess': 0.0006485660887366398, 'inference': 20.061874947153463, 'loss': 3.434360972995406e-05, 'postprocess': 8.425993230993888e-05}
task: 'classify'
top1: 0.5132158398628235
top5: 0.933920681476593

In [ ]:
project="/content/drive/MyDrive/YOLO_MMOTU_RESULTS"
name="yolov12_cls"

In [ ]:
import pandas as pd

csv_path = "/content/drive/MyDrive/YOLO_MMOTU_RESULTS/yolov12_cls/results.csv"
df = pd.read_csv(csv_path)

# Show last epoch (final performance)
df.tail(1)

,epoch,time,train/loss,metrics/accuracy_top1,metrics/accuracy_top5,val/loss,lr/pg0,lr/pg1,lr/pg2
49,50,5643.21,1.48538,0.51322,0.93392,1.44068,0.000027,0.000027,0.000027